std = "lua51"
max_line_length = 140
globals = {
    "CreateFrame",
    "DEFAULT_CHAT_FRAME",
    "UIParent",
    "Minimap",
    "GameTooltip",
    "UISpecialFrames",
    "SlashCmdList",
    "SLASH_DKMENTOR1",
    "SLASH_DKMENTOR2",
    "GetSpecialization",
    "GetSpecializationInfo",
    "UnitClass",
    "UnitAffectingCombat",
    "IsInInstance",
    "InCombatLockdown",
    "GetActionInfo",
    "GetSpellInfo",
    "IsPlayerSpell",
    "IsSpellKnown",
    "GetCVarBool",
    "SetCVar",
    "GetCursorPosition",
    "C_Timer",
    "C_Spell",
    "C_CVar",
    "C_AssistedCombat",
    "C_PartyInfo",
    "C_PvP",
    "_G",
}
