local ADDON_NAME, DKM = ...

DKM = DKM or {}

local clientLocale = (GetLocale and GetLocale()) or "enUS"
local localeOverride = "auto"
local locale = clientLocale
local ptBR = {}

local function NormalizeLanguageOverride(value)
    value = tostring(value or "auto")
    if value == "ptBR" then return "ptBR" end
    if value == "enUS" or value == "enGB" or value == "en" then return "enUS" end
    return "auto"
end

local function ResolveEffectiveLocale(override)
    override = NormalizeLanguageOverride(override)
    local resolved = override == "auto" and clientLocale or override
    if resolved ~= "ptBR" then
        resolved = "enUS"
    end
    return resolved, override
end

-- SavedVariables are normally available while the addon is loading. Reading the
-- preference here means Data/Guides modules that localize static labels during
-- file load also start in the user's selected DK Mentor language after /reload.
if type(_G.DKMentorDB) == "table" then
    locale, localeOverride = ResolveEffectiveLocale(_G.DKMentorDB.languageOverride)
else
    locale, localeOverride = ResolveEffectiveLocale("auto")
end

local function P(en, pt)
    ptBR[en] = pt
end

-- General UI
P("Auto", "Auto")
P("World", "Mundo")
P("Delve", "Imersão")
P("Dungeon", "Masmorra")
P("Raid", "Raide")
P("PvP", "JxJ")
P("Blood", "Sangue")
P("Frost", "Gélido")
P("Unholy", "Profano")
P("Death Knight", "Cavaleiro da Morte")
P("No specialization", "Sem especialização")
P("Change specialization", "Trocar especialização")
P("Click to choose Blood, Frost, or Unholy. Specializations are never changed automatically.", "Clique para escolher Sangue, Gélido ou Profano. As especializações nunca são trocadas automaticamente.")
P("You cannot change specialization during combat.", "Não é possível trocar de especialização durante o combate.")
P("That specialization is not available.", "Essa especialização não está disponível.")
P("WoW did not allow the specialization change.", "O WoW não permitiu a troca de especialização.")
P("Switching specialization to %s...", "Trocando especialização para %s...")
P("CURRENT", "ATUAL")
P("Unknown", "Desconhecida")
P("automatic", "automático")
P("manual", "manual")
P("War Mode active", "Modo de Guerra ativo")
P("Combat", "Combate")
P("Builds", "Builds")
P("Guide", "Guia")
P("Settings", "Configurações")
P("Offensive rotation", "Rotação ofensiva")
P("Build Manager", "Gerenciador de builds")
P("Lich King commentary", "Comentários do Lich King")
P("Survival — when to use it", "Sobrevivência — quando usar")
P("Combat HUDs", "HUDs de combate")
P("Specialization guide", "Guia da especialização")
P("Check action bars", "Verificar barras")
P("Disable native highlight", "Desativar destaque nativo")
P("Enable native highlight", "Ativar destaque nativo")
P("Select source URL", "Selecionar URL da fonte")
P("Personal talent import code (optional; stored locally):", "Código de importação de talentos (opcional; salvo localmente):")
P("Save code", "Salvar código")
P("Clear", "Limpar")
P("Create DKM loadout", "Criar loadout DKM")
P("Choose loadout...", "Escolher loadout...")
P("Choose gear set...", "Escolher conjunto...")
P("Build HUD: ON", "HUD de build: LIGADO")
P("Build HUD: OFF", "HUD de build: DESLIGADO")
P("Talents AUTO: ON", "Talentos AUTO: LIGADO")
P("Talents AUTO: OFF", "Talentos AUTO: DESLIGADO")
P("Gear AUTO: ON", "Equipamento AUTO: LIGADO")
P("Gear AUTO: OFF", "Equipamento AUTO: DESLIGADO")
P("Coach HUD: ON", "HUD do Coach: LIGADO")
P("Coach HUD: OFF", "HUD do Coach: DESLIGADO")
P("Buff bar: ON", "Barra de buffs: LIGADA")
P("Buff bar: OFF", "Barra de buffs: DESLIGADA")
P("Ability bar: ON", "Barra de habilidades: LIGADA")
P("Ability bar: OFF", "Barra de habilidades: DESLIGADA")
P("DK resources: ON", "Recursos do DK: LIGADOS")
P("DK resources: OFF", "Recursos do DK: DESLIGADOS")
P("External buffs: ON", "Buffs externos: LIGADOS")
P("External buffs: OFF", "Buffs externos: DESLIGADOS")
P("Debuffs: ON", "Debuffs: LIGADOS")
P("Debuffs: OFF", "Debuffs: DESLIGADOS")
P("Drag to move", "Arraste para mover")
P("Enable commentary", "Ativar comentários")
P("Disable commentary", "Desativar comentários")
P("Voice mapping...", "Mapear vozes...")
P("Preview voice", "Ouvir prévia")
P("Situations: ON", "Situações: LIGADAS")
P("Situations: OFF", "Situações: DESLIGADAS")
P("Frequency: %s", "Frequência: %s")
P("Low", "Baixa")
P("Normal", "Normal")
P("High", "Alta")
P("Enabled", "Ativado")
P("Disabled", "Desativado")
P("on", "ligado")
P("off", "desligado")
P("Build", "Build")
P("Gear", "Equipamento")
P("Guide", "Guia")
P("not bound", "não associado")
P("not detected", "não detectada")
P("saved set missing", "conjunto salvo ausente")
P("TALENTS AUTO", "TALENTOS AUTO")
P("TALENTS MANUAL", "TALENTOS MANUAL")
P("GEAR AUTO", "EQUIPAMENTO AUTO")
P("GEAR MANUAL", "EQUIPAMENTO MANUAL")
P("GEAR QUEUED", "EQUIPAMENTO NA FILA")
P("TALENTS QUEUED", "TALENTOS NA FILA")
P("READY", "PRONTO")
P("Talents", "Talentos")
P("Runeforge", "Forja Rúnica")
P("Ghoul", "Carniçal")
P("DK Ready Check", "Verificação DK Pronto")
P("DK READY", "DK PRONTO")
P("DK NOT READY: %s", "DK NÃO PRONTO: %s")
P("DK NOT READY: %d ISSUES", "DK NÃO PRONTO: %d PENDÊNCIAS")
P("TALENTS", "TALENTOS")
P("GEAR", "EQUIPAMENTO")
P("RUNEFORGE", "FORJA RÚNICA")
P("GHOUL", "CARNIÇAL")
P("Main hand", "Mão principal")
P("Off hand", "Mão secundária")
P("No weapon equipped", "Nenhuma arma equipada")
P("Checking runeforge...", "Verificando Forja Rúnica...")
P("Weapon has a non-Runeforge enchant", "A arma possui um encantamento que não é de Forja Rúnica")
P("Runeforge missing", "Forja Rúnica ausente")
P("Not required", "Não necessário")
P("Paused while in a vehicle", "Pausado durante o uso de veículo")
P("Paused while travelling", "Pausado durante a viagem")
P("Ghoul missing", "Carniçal ausente")
P("Ghoul is dead", "Carniçal morto")
P("Ghoul active", "Carniçal ativo")
P("Ready Check unavailable", "Verificação de prontidão indisponível")
P("No talent loadout mapped for this content", "Nenhum loadout de talentos associado para este conteúdo")
P("Waiting for talent loadout: %s", "Aguardando loadout de talentos: %s")
P("Expected talent loadout: %s", "Loadout de talentos esperado: %s")
P("Talent loadout: %s", "Loadout de talentos: %s")
P("No equipment set mapped for this content", "Nenhum conjunto de equipamento associado para este conteúdo")
P("Mapped equipment set is missing", "O conjunto de equipamento associado não existe mais")
P("Expected equipment set: %s", "Conjunto de equipamento esperado: %s")
P("Equipment set: %s", "Conjunto de equipamento: %s")
P("Runeforge Guard checks for a Death Knight Runeforge on each equipped weapon; it does not claim that one rune is always the best for every build.", "O Guardião de Forja Rúnica verifica se cada arma equipada possui uma Forja Rúnica de Cavaleiro da Morte; ele não afirma que uma única runa seja sempre a melhor para todas as builds.")
P("/dkm ready — show the DK Ready Check details", "/dkm ready — mostrar os detalhes da verificação DK Pronto")
P("Rune of the Fallen Crusader", "Runa do Cruzado Caído")
P("Rune of Razorice", "Runa da Gelâmina")
P("Rune of the Stoneskin Gargoyle", "Runa da Gárgula Litopele")
P("Rune of Sanguination", "Runa da Sangradura")
P("Rune of Spellwarding", "Runa de Proteção Mágica")
P("Rune of Hysteria", "Runa da Histeria")
P("Rune of Unending Thirst", "Runa da Sede Infinita")
P("Rune of the Apocalypse", "Runa do Apocalipse")
P("WAIT", "AGUARDE")
P("ACTIVE", "ATIVO")
P("No tracked buffs", "Nenhum buff monitorado")
P("No tracked abilities", "Nenhuma habilidade monitorada")
P("Buffs", "Buffs")
P("Abilities", "Habilidades")
P("DK Buffs", "Buffs do DK")
P("DK Resources", "Recursos do DK")
P("Runes", "Runas")
P("External Buffs", "Buffs externos")
P("Debuffs", "Debuffs")
P("Aura", "Aura")
P("Missing", "Ausente")
P("talent", "talento")
P("Data %s • Patch %s • /dkm help • Guidance only; no ability is used automatically.", "Dados %s • Patch %s • /dkm help • Apenas orientação; nenhuma habilidade é usada automaticamente.")
P("The offensive highlight comes from Blizzard Assisted Combat. DK Mentor does not calculate a custom APL during combat.", "O destaque ofensivo vem do Combate Assistido da Blizzard. O DK Mentor não calcula uma APL própria durante o combate.")
P("Native highlight enabled.", "Destaque nativo ativado.")
P("Follow the blue glow on your action bars for the next offensive ability.", "Siga o brilho azul nas barras de ação para a próxima habilidade ofensiva.")
P("Native highlight disabled.", "Destaque nativo desativado.")
P("Enable it to receive the offensive recommendation provided by the game client.", "Ative para receber a recomendação ofensiva fornecida pelo próprio cliente do jogo.")
P("Native combat assistant is currently unavailable.", "O assistente de combate nativo não está disponível no momento.")
P("No build focus is available for this specialization.", "Nenhuma recomendação de build está disponível para esta especialização.")
P("Select Blood, Frost, or Unholy and refresh the interface.", "Selecione Sangue, Gélido ou Profano e recarregue a interface.")
P("No saved WoW loadout", "Nenhum loadout do WoW salvo")
P("No saved equipment set", "Nenhum conjunto de equipamento salvo")
P("Build recommendation", "Recomendação de build")
P("No external source URL for this profile", "Este perfil não possui URL externa")
P("PvP guide:", "Guia JxJ:")
P("Guide code:", "Código do guia:")
P("Copy the current import code from the cited guide and save it here if you want a local reference.", "Copie o código de importação atual do guia citado e salve aqui se quiser manter uma referência local.")
P("Saved locally. Import it into WoW, save that WoW loadout, then bind it below.", "Salvo localmente. Importe no WoW, salve o loadout no jogo e depois associe-o abaixo.")
P("DKM loadout: none", "Loadout DKM: nenhum")
P("Gear: none", "Equipamento: nenhum")
P("Gear set missing", "Conjunto de equipamento ausente")
P("Map an existing WoW talent loadout and Equipment Set to each specialization/content profile. Talent and gear auto-switching are independent and wait until combat ends when WoW blocks the change.", "Associe um loadout de talentos e um conjunto de equipamento existentes do WoW a cada perfil de especialização/conteúdo. A troca automática de talentos e equipamento é independente e espera o combate terminar quando o WoW bloquear a alteração.")
P("Map an existing WoW Equipment Set to %s / %s. This mapping is used by Gear AUTO.", "Associe um conjunto de equipamento existente do WoW a %s / %s. Essa associação é usada pelo Equipamento AUTO.")
P("Talent Loadout Mapping", "Associação de loadouts de talentos")
P("Map an existing WoW talent loadout to %s / %s. This mapping is used by Talents AUTO.", "Associe um loadout de talentos existente do WoW a %s / %s. Essa associação é usada por Talentos AUTO.")
P("Use current loadout", "Usar loadout atual")
P("Create DKM copy", "Criar cópia DKM")
P("No saved WoW talent loadouts were found for this specialization.", "Nenhum loadout de talentos salvo do WoW foi encontrado para esta especialização.")
P("Click a saved WoW loadout to map it. The same loadout can be reused for multiple content types.", "Clique em um loadout salvo do WoW para associá-lo. O mesmo loadout pode ser reutilizado em vários tipos de conteúdo.")
P("Loadout %s", "Loadout %s")
P("Equipment Set Mapping", "Associação de conjuntos de equipamento")
P("Use currently equipped set", "Usar conjunto equipado")
P("Refresh list", "Atualizar lista")
P("No saved WoW Equipment Sets were found. Create one in the Character > Equipment Manager first.", "Nenhum conjunto de equipamento salvo foi encontrado. Crie um primeiro em Personagem > Gerenciador de Equipamentos.")
P("Click a saved WoW set to map it. DK Mentor does not duplicate it.", "Clique em um conjunto salvo do WoW para associá-lo. O DK Mentor não cria uma cópia.")
P("MAPPED", "ASSOCIADO")
P("EQUIPPED", "EQUIPADO")
P("%d missing", "%d ausente(s)")
P("%d/%d equipped", "%d/%d equipado(s)")
P("Lich King Voice Mapping", "Mapeamento de voz do Lich King")
P("Choose Random, Disabled, or a specific installed voice for each situation. Use Preview to identify a line; DK Mentor stores no quote text.", "Escolha Aleatória, Desativada ou uma voz instalada específica para cada situação. Use Prévia para identificar a fala; o DK Mentor não armazena o texto das falas.")
P("Preview", "Prévia")
P("Random", "Aleatória")
P("Reset all to Random", "Redefinir tudo para Aleatória")
P("A selected line may be unavailable in some client locales; Preview lets you verify it.", "Uma fala selecionada pode não existir em alguns idiomas do cliente; use Prévia para verificar.")
P("Voice %d/%d", "Voz %d/%d")
P("Uses installed WoW voice resources; no audio files are bundled.", "Usa recursos de voz já instalados pelo WoW; nenhum arquivo de áudio é incluído.")
P("Left-click: open/close", "Clique esquerdo: abrir/fechar")
P("Right-click: toggle survival coach", "Clique direito: ligar/desligar o Coach de sobrevivência")
P("Shift-right-click: toggle Lich King commentary", "Shift + clique direito: ligar/desligar os comentários do Lich King")
P("Drag: move around the minimap", "Arraste: mover ao redor do minimapa")
P("DK Mentor Build HUD", "HUD de build do DK Mentor")
P("Shows your Death Knight specialization, detected content, active WoW talent loadout, and associated equipment set.", "Mostra a especialização do Cavaleiro da Morte, o conteúdo detectado, o loadout de talentos ativo e o conjunto de equipamento associado.")
P("Drag to move. Toggle it from Settings or with /dkm hud.", "Arraste para mover. Ative ou desative em Configurações ou com /dkm hud.")
P("Right-click: open or close DK Mentor", "Clique direito: abrir ou fechar o DK Mentor")
P("The Buff Bar shows tracked Death Knight buffs. Active buffs are bright; inactive tracked buffs stay dim so the bar remains easy to position.", "A Barra de Buffs mostra buffs monitorados do Cavaleiro da Morte. Buffs ativos ficam destacados; os inativos permanecem apagados para facilitar o posicionamento da barra.")
P("The Ability Bar shows important known abilities. Bright means ready, dim means cooling down or currently unusable.", "A Barra de Habilidades mostra habilidades importantes conhecidas. Brilhante significa pronta; apagada significa em recarga ou indisponível no momento.")
P("Both bars are movable and can be disabled at any time.", "As duas barras podem ser movidas e desativadas a qualquer momento.")
P("Show or hide each HUD independently. Drag a HUD directly to place it above your action bars or anywhere else.", "Mostre ou esconda cada HUD de forma independente. Arraste um HUD para colocá-lo acima das barras de ação ou em qualquer outro lugar.")

-- Coach/adaptive health
P("STABLE", "ESTÁVEL")
P("RECOVER", "RECUPERAR")
P("DANGER", "PERIGO")
P("CRITICAL", "CRÍTICO")
P("Health: %d%% • %s", "Vida: %d%% • %s")
P("USE NOW", "USE AGORA")
P("critical health", "vida crítica")
P("heal immediately", "cure-se imediatamente")
P("if pressure continues", "se a pressão continuar")
P("recover recent damage", "recupere o dano recente")
P("DEFENSIVE", "DEFENSIVO")
P("if health keeps falling", "se a vida continuar caindo")
P("MITIGATE", "MITIGAR")
P("before the next hit", "antes do próximo golpe")
P("PANIC", "EMERGÊNCIA")
P("if talented / needed", "se tiver o talento / necessário")
P("BACKUP HEAL", "CURA RESERVA")
P("after meaningful damage", "após dano relevante")
P("PREPARE", "PREPARAR")
P("before another heavy hit", "antes de outro golpe pesado")
P("HOLD READY", "MANTENHA PRONTO")
P("for sustained pressure", "para pressão prolongada")
P("before incoming magic", "antes de dano mágico")
P("for a bigger spike", "para um pico maior")
P("USE", "USAR")

-- Survival tags and descriptions
P("HEAL", "CURA")
P("MAGIC", "MAGIA")
P("EMERGENCY", "EMERGÊNCIA")
P("STRONG HEAL", "CURA FORTE")
P("INTERRUPT", "INTERRUPÇÃO")
P("CONTROL", "CONTROLE")
P("PANIC BUTTON", "BOTÃO DE PÂNICO")
P("POSITION", "POSICIONAMENTO")
P("PERSONAL", "PESSOAL")
P("GROUP", "GRUPO")
P("STOP PACK", "PARAR GRUPO")
P("MECHANIC", "MECÂNICA")
P("RAID", "RAIDE")
P("SELF-HEAL", "AUTOCURA")
P("MOVEMENT", "MOVIMENTO")
P("UTILITY", "UTILIDADE")
P("MAGIC / CC", "MAGIA / CC")
P("STUN / BURST", "ATORDOAR / BURST")
P("SUSTAIN", "SUSTENTAÇÃO")
P("SURVIVE", "SOBREVIVER")
P("CORE", "ESSENCIAL")
P("BEFORE", "ANTES")
P("HEALTH / HEAL", "VIDA / CURA")
P("LARGE PACK", "GRUPO GRANDE")
P("BONE SHIELD", "ESCUDO ÓSSEO")
P("AFTER DAMAGE", "APÓS O DANO")
P("BEFORE DAMAGE", "ANTES DO DANO")
P("OPEN PACK", "ABRIR GRUPO")
P("AFTER THE HIT", "APÓS O GOLPE")
P("TANK BUSTER", "GOLPE DE TANQUE")
P("HARD PULL", "PULL PERIGOSO")
P("AMPLIFY", "AMPLIFICAR")
P("PLANNED", "PLANEJADO")
P("STRONG WINDOW", "JANELA FORTE")
P("PREVENT", "PREVENIR")
P("CC / MAGIC", "CC / MAGIA")
P("MAX HEALTH", "VIDA MÁXIMA")
P("SEQUENCE", "SEQUÊNCIA")
P("AFTER", "DEPOIS")
P("PLAN", "PLANEJAR")
P("Use after meaningful damage. Avoid spending all Runic Power when a dangerous fight is about to begin.", "Use após dano relevante. Evite gastar todo o Poder Rúnico quando uma luta perigosa estiver prestes a começar.")
P("Use shortly before predictable magic damage, a magic debuff, or magic crowd control.", "Use pouco antes de dano mágico previsível, um debuff mágico ou controle de grupo mágico.")
P("Use against very high damage, during a dangerous stun, or when remaining exposed would be lethal.", "Use contra dano muito alto, durante um atordoamento perigoso ou quando continuar exposto seria letal.")
P("Emergency healing when Death Strike will not be enough.", "Cura de emergência quando Golpe da Morte não for suficiente.")
P("Stopping a dangerous cast is usually better than taking the damage and spending a defensive cooldown.", "Interromper um lançamento perigoso normalmente é melhor do que receber o dano e gastar um defensivo.")
P("Stop several enemies or a cast when your interrupt is unavailable.", "Pare vários inimigos ou um lançamento quando sua interrupção não estiver disponível.")
P("Use after a heavy hit and preserve Runic Power before elites or large groups.", "Use após um golpe pesado e preserve Poder Rúnico antes de elites ou grupos grandes.")
P("Anticipate bursts and magic effects. Using it before the effect is usually more valuable than using it afterward.", "Antecipe bursts e efeitos mágicos. Usar antes do efeito normalmente vale mais do que usar depois.")
P("Use on large pulls, during dangerous stuns, or when your companion cannot stabilize the fight.", "Use em pulls grandes, durante atordoamentos perigosos ou quando seu companheiro não conseguir estabilizar a luta.")
P("A final healing option to survive until the next Death Strike.", "Uma última opção de cura para sobreviver até o próximo Golpe da Morte.")
P("Prioritize enemy heals, crowd control, and high-damage casts.", "Priorize curas inimigas, controles de grupo e lançamentos de alto dano.")
P("Use against knockbacks, pulls, and slows, or to leave a dangerous area safely.", "Use contra repulsões, puxões e lentidões, ou para sair de uma área perigosa com segurança.")
P("Stop the priority cast. Preventing damage reduces pressure on the healer.", "Interrompa o lançamento prioritário. Prevenir dano reduz a pressão sobre o curador.")
P("Use before a targeted magic mechanic or a preventable magic debuff.", "Use antes de uma mecânica mágica direcionada ou de um debuff mágico evitável.")
P("Use when several party members will take magic damage at the same time.", "Use quando vários membros do grupo forem receber dano mágico ao mesmo tempo.")
P("Use during focused damage, a dangerous stun, or when the healer is under pressure.", "Use durante dano focado, um atordoamento perigoso ou quando o curador estiver sob pressão.")
P("Use after the damage spike. Avoid compromising your rotation when healing is not needed.", "Use após o pico de dano. Evite comprometer sua rotação quando a cura não for necessária.")
P("Interrupt several enemy actions when Mind Freeze is on cooldown.", "Interrompa várias ações inimigas quando Congelar Mente estiver em recarga.")
P("Use before predictable magic damage or when the shield can prevent a debuff.", "Use antes de dano mágico previsível ou quando o escudo puder impedir um debuff.")
P("Place it on the group before a major source of magic damage.", "Coloque sobre o grupo antes de uma grande fonte de dano mágico.")
P("Reserve it for a dangerous overlap, a stun, or potentially lethal damage.", "Reserve para uma sobreposição perigosa de mecânicas, um atordoamento ou dano potencialmente letal.")
P("Recover after a spike to reduce pressure on healers.", "Recupere-se após um pico para reduzir a pressão sobre os curadores.")
P("Use to resist forced movement or cross a movement window safely.", "Use para resistir a movimento forçado ou atravessar uma janela de movimentação com segurança.")
P("Use combat resurrection only when the group call justifies spending the charge.", "Use a ressurreição em combate apenas quando a chamada do grupo justificar gastar a carga.")
P("Use before incoming magic crowd control or a caster burst window, not after the control has landed.", "Use antes de um controle mágico ou janela de burst de conjurador, não depois que o controle já acertou.")
P("Use during a dangerous stun or the enemy team's highest pressure window.", "Use durante um atordoamento perigoso ou a maior janela de pressão do time inimigo.")
P("Use after heavy damage. Preserve Runic Power when you are likely to be the next target.", "Use após dano pesado. Preserve Poder Rúnico quando você provavelmente será o próximo alvo.")
P("Use when you are in real danger and the next Death Strike will not arrive in time.", "Use quando estiver realmente em perigo e o próximo Golpe da Morte não chegar a tempo.")
P("Use according to the selected talent to deny the appropriate crowd-control effects.", "Use conforme o talento selecionado para negar os efeitos de controle apropriados.")
P("Reduce pressure by creating distance. Combine with Death Grip to protect yourself or an ally.", "Reduza a pressão criando distância. Combine com Garra da Morte para proteger você ou um aliado.")
P("Enter combat with Bone Shield and refresh it before the stacks are exhausted.", "Entre em combate com Escudo Ósseo e renove antes que as cargas acabem.")
P("Use after damage instead of merely because it is available. It is your primary active recovery tool.", "Use após receber dano, não apenas porque está disponível. É sua principal ferramenta ativa de recuperação.")
P("Use before a heavy hit or before taking damage from several enemies.", "Use antes de um golpe pesado ou antes de receber dano de vários inimigos.")
P("Activate before a dangerous window or to amplify recovery when your health begins to fall.", "Ative antes de uma janela perigosa ou para amplificar a recuperação quando sua vida começar a cair.")
P("Use early in a dangerous pull to gain control and stability.", "Use cedo em um pull perigoso para ganhar controle e estabilidade.")
P("Anticipate important magic damage and magic effects.", "Antecipe dano mágico importante e efeitos mágicos.")
P("Maintain stacks before engaging elites and large groups.", "Mantenha cargas antes de enfrentar elites e grupos grandes.")
P("Wait for the damage spike and convert Runic Power into recovery.", "Espere o pico de dano e converta Poder Rúnico em recuperação.")
P("Reduce a telegraphed hit or the opening damage of a large pull.", "Reduza um golpe anunciado ou o dano inicial de um pull grande.")
P("Use early in dangerous encounters. Holding it until you are almost dead wastes much of its value.", "Use cedo em encontros perigosos. Guardar até quase morrer desperdiça grande parte do valor.")
P("Use before or during a window that will require several consecutive heals.", "Use antes ou durante uma janela que exigirá várias curas consecutivas.")
P("Protect yourself from predictable bursts, debuffs, and magic crowd control.", "Proteja-se de bursts previsíveis, debuffs e controles mágicos.")
P("Do not begin an important pull unprepared. Keep your stacks stable.", "Não comece um pull importante despreparado. Mantenha suas cargas estáveis.")
P("Absorb the hit, then recover at the correct moment.", "Receba o golpe e recupere-se no momento correto.")
P("Use before predictable physical damage or when entering a large pack.", "Use antes de dano físico previsível ou ao entrar em um grupo grande.")
P("Use at the beginning of pulls that truly threaten you, not as a late panic button.", "Use no início de pulls que realmente ameacem você, não como um botão de pânico tardio.")
P("Use when sustained damage will require more maximum health and stronger incoming healing.", "Use quando dano sustentado exigir mais vida máxima e curas recebidas mais fortes.")
P("Help the group during shared magic damage when positioning allows it.", "Ajude o grupo durante dano mágico compartilhado quando o posicionamento permitir.")
P("Maintain mitigation before taking the boss or performing a tank swap.", "Mantenha a mitigação antes de assumir o chefe ou fazer uma troca de tanque.")
P("Use after the heavy attack and plan Runic Power for each boss hit.", "Use após o ataque pesado e planeje o Poder Rúnico para cada golpe do chefe.")
P("Reduce a predictable tank buster before it lands.", "Reduza um golpe pesado de tanque antes que ele acerte.")
P("Pair it with a known hit or damage sequence instead of waiting only for low health.", "Combine com um golpe conhecido ou sequência de dano em vez de esperar apenas a vida ficar baixa.")
P("Use as a planned cooldown for tank damage and offensive generation.", "Use como recarga planejada para dano de tanque e geração ofensiva.")
P("Anticipate magic damage and effects that can be absorbed.", "Antecipe dano mágico e efeitos que podem ser absorvidos.")
P("Preserve Runic Power and use it after the enemy damage window.", "Preserve Poder Rúnico e use após a janela de dano inimiga.")
P("Use before magic crowd control and burst.", "Use antes de controle mágico e burst.")
P("Use during the largest pressure window or a dangerous stun.", "Use durante a maior janela de pressão ou um atordoamento perigoso.")
P("Buy time for several heals and support from your group.", "Ganhe tempo para várias curas e apoio do seu grupo.")
P("Use as a last resort when normal recovery will not arrive in time.", "Use como último recurso quando a recuperação normal não chegar a tempo.")
P("Reduce pressure on yourself or an ally by limiting enemy mobility.", "Reduza a pressão sobre você ou um aliado limitando a mobilidade inimiga.")

-- Short coach timings
P("after damage", "após o dano")
P("before the effect", "antes do efeito")
P("burst / stun", "burst / atordoamento")
P("after the hit", "após o golpe")
P("before the burst", "antes do burst")
P("large pack / stun", "grupo grande / atordoamento")
P("interrupt first", "interrompa primeiro")
P("magic on you", "magia em você")
P("after the spike", "após o pico")
P("before mechanic", "antes da mecânica")
P("magic damage", "dano mágico")
P("lethal overlap", "sobreposição letal")
P("use before", "use antes")
P("use at peak", "use no pico")
P("before the hit", "antes do golpe")
P("dangerous window", "janela perigosa")
P("use early", "use cedo")
P("amplify healing", "amplifique a cura")
P("tank buster", "golpe de tanque")
P("sustained damage", "dano sustentado")
P("recover the hit", "recupere o golpe")
P("predicted hit", "golpe previsto")
P("strong window", "janela forte")
P("preserve resource", "preserve recurso")

-- Build names / notes
P("Blood — Open World / Solo", "Sangue — Mundo aberto / Solo")
P("Blood — Delves", "Sangue — Imersões")
P("Blood — Dungeon / Mythic+", "Sangue — Masmorra / Mítica+")
P("Blood — Raid", "Sangue — Raide")
P("Blood — War Mode / World PvP", "Sangue — Modo de Guerra / JxJ no mundo")
P("Frost — Open World / Solo", "Gélido — Mundo aberto / Solo")
P("Frost — Delves (Deathbringer)", "Gélido — Imersões (Arauto da Morte)")
P("Frost — Dungeon / Mythic+", "Gélido — Masmorra / Mítica+")
P("Frost — Raid", "Gélido — Raide")
P("Frost PvP — Deathbringer", "Gélido JxJ — Arauto da Morte")
P("Frost PvP — Rider", "Gélido JxJ — Cavaleiro")
P("Unholy — Open World", "Profano — Mundo aberto")
P("Unholy — Delves / Sustained AoE", "Profano — Imersões / Área sustentada")
P("Unholy — Mythic+ / Dungeon", "Profano — Mítica+ / Masmorra")
P("Unholy — Mythic+ Alternate", "Profano — Mítica+ alternativa")
P("Unholy — Single Target / Raid", "Profano — Alvo único / Raide")
P("Unholy PvP — Pet", "Profano JxJ — Mascote")
P("Unholy PvP — Disease", "Profano JxJ — Doenças")
P("Use the current Blood PvE guide as the baseline, then favor comfort, self-sustain, and utility for solo pulls.", "Use o guia PvE atual de Sangue como base e priorize conforto, sustentação própria e utilidade para pulls solo.")
P("Use the guide's current Delve-oriented direction, emphasizing self-sustain and practical defensive coverage.", "Use a direção atual do guia para Imersões, priorizando sustentação própria e cobertura defensiva prática.")
P("Use the current Mythic+ recommendation as the dungeon baseline, with encounter-specific utility adjusted as needed.", "Use a recomendação atual de Mítica+ como base para masmorras e ajuste a utilidade conforme o encontro.")
P("Use the current raid recommendation for boss tanking, then move flexible utility points for encounter mechanics.", "Use a recomendação atual de raide para tankar chefes e mova pontos flexíveis de utilidade conforme as mecânicas.")
P("Icy Veins does not maintain a dedicated Blood arena guide; this points to the current Blood talent guide and its War Mode/PvP talent guidance.", "O Icy Veins não mantém um guia dedicado de arena para Sangue; este perfil aponta para o guia atual de talentos de Sangue e suas orientações de Modo de Guerra/JxJ.")
P("War Mode reference. Blood is not presented here as an arena-meta specialization.", "Referência para Modo de Guerra. Sangue não é apresentado aqui como uma especialização meta de arena.")
P("Use the current Frost PvE recommendation as a starting point, retaining utility and Runic Power flexibility for solo survival.", "Use a recomendação PvE atual de Gélido como ponto de partida, mantendo utilidade e flexibilidade de Poder Rúnico para sobreviver solo.")
P("The current guide recommends Deathbringer for Delves, giving frequent power for tougher enemies while retaining strong cleave.", "O guia atual recomenda Arauto da Morte para Imersões, oferecendo poder frequente contra inimigos mais resistentes e mantendo bom dano em múltiplos alvos.")
P("Use the current Mythic+ recommendation. The guide currently keeps Frost's overall direction close to its raid setup with limited swaps.", "Use a recomendação atual de Mítica+. O guia mantém a direção geral de Gélido próxima da configuração de raide, com poucas trocas.")
P("Use the current raid recommendation for boss damage and adjust utility or cleave options for encounter needs.", "Use a recomendação atual de raide para dano em chefes e ajuste utilidade ou cleave conforme o encontro.")
P("Current Icy Veins PvP guide option focused on stronger burst setup and coordinated pressure.", "Opção atual do guia JxJ do Icy Veins focada em burst mais forte e pressão coordenada.")
P("Current Icy Veins PvP alternative focused more on sustained pressure and a less all-in burst profile.", "Alternativa atual do Icy Veins focada em pressão sustentada e menos dependência de uma única janela de burst.")
P("Current 12.1 PvP guide. PvP talents remain matchup-dependent.", "Guia JxJ atual da 12.1. Talentos JxJ continuam dependendo do confronto.")
P("Use the guide's current Open World recommendation for questing and solo play, preserving enough resources to recover with Death Strike when pressured.", "Use a recomendação atual de Mundo Aberto para missões e jogo solo, preservando recursos suficientes para recuperar vida com Golpe da Morte quando pressionado.")
P("The current guide points Delve players toward its Mythic+ builds, with a simpler sustained-AoE direction suitable for general Delve play.", "O guia atual direciona jogadores de Imersões para builds de Mítica+, com uma opção mais simples de dano em área sustentado adequada ao conteúdo.")
P("Use the current Mythic+ recommendation as the default dungeon profile.", "Use a recomendação atual de Mítica+ como perfil padrão de masmorra.")
P("Use the guide's alternate current Mythic+ direction when you prefer that playstyle and its timing requirements.", "Use a alternativa atual de Mítica+ quando preferir esse estilo e seus requisitos de tempo.")
P("Use the current Single Target recommendation as the raid baseline.", "Use a recomendação atual de alvo único como base para raides.")
P("Current Icy Veins PvP option focused on pet damage and single-target pressure.", "Opção JxJ atual do Icy Veins focada em dano do mascote e pressão em alvo único.")
P("Current Icy Veins PvP alternative for rot pressure; the guide currently describes it as weaker than the pet setup.", "Alternativa JxJ atual do Icy Veins para pressão por dano contínuo; o guia atualmente a descreve como mais fraca que a configuração de mascote.")
P("Current 12.1 PvP guide. PvP talents should be adjusted for the opposing composition.", "Guia JxJ atual da 12.1. Os talentos JxJ devem ser ajustados conforme a composição adversária.")
P("%s • %s • guide updated %s", "%s • %s • guia atualizado em %s")
P("reviewed for %s on %s", "revisado para %s em %s")
P("data package %s", "pacote de dados %s")

-- Voice mapping labels
P("Login / Reload", "Login / Recarregar")
P("New zone", "Nova área")
P("Combat starts", "Início do combate")
P("Combat victory", "Vitória em combate")
P("Boss starts", "Início de chefe")
P("Boss defeated", "Chefe derrotado")
P("Player dies", "Jogador morre")
P("Resurrection", "Ressurreição")
P("Mounting", "Montaria")
P("Hearthstone", "Pedra de Regresso")
P("Going AFK", "Entrando em AFK")
P("Returning from AFK", "Voltando do AFK")
P("Raise Dead", "Reviver Morto")
P("Raise Ally", "Reviver Aliado")
P("Army of the Dead", "Exército dos Mortos")
P("Dark Transformation", "Transformação Negra")
P("Death's Advance", "Avanço da Morte")
P("Death Grip", "Garra da Morte")
P("Death and Decay", "Morte e Decomposição")
P("Death Gate", "Portão da Morte")
P("Asphyxiate", "Asfixiar")
P("Blinding Sleet", "Saraivada Cegante")
P("Mind Freeze", "Congelar Mente")
P("Chains of Ice", "Correntes de Gelo")
P("Pillar of Frost", "Pilar de Gelo")
P("Breath of Sindragosa", "Sopro de Sindragosa")
P("Frostwyrm's Fury", "Fúria da Serpe Gélida")
P("Apocalypse", "Apocalipse")
P("Major defensive", "Defensivo importante")

-- Guide
P("Death Knight fundamentals", "Fundamentos do Cavaleiro da Morte")
P("Runes and Runic Power", "Runas e Poder Rúnico")
P("Your abilities spend Runes to create Runic Power, then spend Runic Power on finishers and recovery. Avoid wasting either resource: keep Runes cycling and leave enough Runic Power for Death Strike when survival matters.", "Suas habilidades gastam Runas para gerar Poder Rúnico e depois gastam Poder Rúnico em finalizadores e recuperação. Evite desperdiçar qualquer um dos recursos: mantenha as Runas girando e preserve Poder Rúnico suficiente para Golpe da Morte quando a sobrevivência importar.")
P("Death Strike is your universal recovery tool", "Golpe da Morte é sua ferramenta universal de recuperação")
P("For Frost and Unholy, Death Strike is mainly a survival decision. Use it after meaningful damage instead of pressing it whenever possible. Blood is different: Death Strike is a central part of active tanking and should be timed after dangerous hits.", "Para Gélido e Profano, Golpe da Morte é principalmente uma decisão de sobrevivência. Use após dano relevante em vez de apertar sempre que possível. Sangue é diferente: Golpe da Morte é parte central do tank ativo e deve ser usado no tempo certo após golpes perigosos.")
P("Control prevents damage", "Controle evita dano")
P("Mind Freeze, Death Grip, Chains of Ice, Asphyxiate, and Blinding Sleet can prevent far more damage than a late defensive. Interrupt priority casts first and use control to reduce the number of enemies acting at once.", "Congelar Mente, Garra da Morte, Correntes de Gelo, Asfixiar e Saraivada Cegante podem evitar muito mais dano do que um defensivo tardio. Interrompa lançamentos prioritários primeiro e use controle para reduzir quantos inimigos agem ao mesmo tempo.")
P("Core defensives", "Defensivos principais")
P("Anti-Magic Shell is strongest before magic damage or magic crowd control. Icebound Fortitude is your major emergency defensive and can also help during dangerous stuns. Death's Advance helps against forced movement and slows.", "Carapaça Antimagia é mais forte antes de dano mágico ou controle mágico. Fortitude Congélida é seu grande defensivo de emergência e também ajuda durante atordoamentos perigosos. Avanço da Morte ajuda contra movimento forçado e lentidões.")
P("Frost Death Knight", "Cavaleiro da Morte Gélido")
P("Frost turns Runes into hard-hitting weapon attacks and Runic Power into Frost Strike or other spenders. The spec rewards reacting to procs without overcapping resources.", "Gélido transforma Runas em ataques de arma muito fortes e Poder Rúnico em Golpe Gélido ou outros gastos. A especialização recompensa reagir aos procs sem estourar o limite dos recursos.")
P("Killing Machine and Rime", "Máquina Assassina e Geada")
P("Killing Machine makes your next Obliterate especially valuable, while Rime empowers a free Howling Blast. React to these procs quickly, but do not create resource waste just to consume them instantly.", "Máquina Assassina torna seu próximo Obliterar especialmente valioso, enquanto Geada fortalece uma Rajada Uivante gratuita. Reaja aos procs rapidamente, mas não desperdice recursos apenas para consumi-los imediatamente.")
P("Cooldown windows", "Janelas de recarga")
P("Pillar of Frost defines an important damage window. Enter it with resources available, keep attacking, and avoid spending the entire window moving or recovering from preventable mechanics.", "Pilar de Gelo define uma importante janela de dano. Entre nela com recursos disponíveis, continue atacando e evite gastar a janela inteira se movendo ou se recuperando de mecânicas evitáveis.")
P("Beginner priority", "Prioridade para iniciantes")
P("Keep Runes cycling, react to Killing Machine and Rime, avoid capping Runic Power, use the native Assisted Combat glow for offensive sequencing, and reserve enough Runic Power for Death Strike when solo content becomes dangerous.", "Mantenha as Runas girando, reaja a Máquina Assassina e Geada, evite atingir o limite de Poder Rúnico, use o brilho do Combate Assistido para a sequência ofensiva e preserve Poder Rúnico suficiente para Golpe da Morte quando o conteúdo solo ficar perigoso.")
P("Blood Death Knight", "Cavaleiro da Morte Sangue")
P("Blood survives by preparing mitigation and then recovering after damage. Your health moving up and down is normal; the goal is to control those swings instead of reacting too late.", "Sangue sobrevive preparando mitigação e depois se recuperando após o dano. Sua vida subir e descer é normal; o objetivo é controlar essas oscilações em vez de reagir tarde demais.")
P("Bone Shield", "Escudo Ósseo")
P("Keep Bone Shield active before important pulls. Do not enter a dangerous pack with no stacks if you can prepare beforehand.", "Mantenha Escudo Ósseo ativo antes de pulls importantes. Não entre em um grupo perigoso sem cargas se puder se preparar antes.")
P("Death Strike timing", "Tempo do Golpe da Morte")
P("Death Strike is most valuable after a significant hit. Plan Runic Power around predictable tank damage instead of spending it without purpose.", "Golpe da Morte é mais valioso após um golpe significativo. Planeje o Poder Rúnico em torno do dano previsível de tanque em vez de gastá-lo sem propósito.")
P("Use cooldowns early enough", "Use recargas cedo o suficiente")
P("Vampiric Blood, Dancing Rune Weapon, Rune Tap, and Anti-Magic Shell are tools to prevent a crisis. A defensive used before a dangerous window is usually worth more than one pressed at nearly zero health.", "Sangue Vampírico, Arma Rúnica Dançante, Golpe Rúnico e Carapaça Antimagia são ferramentas para evitar uma crise. Um defensivo usado antes de uma janela perigosa normalmente vale mais do que um apertado quase sem vida.")
P("Unholy Death Knight", "Cavaleiro da Morte Profano")
P("Unholy combines diseases, wounds, pets, and Runic Power spenders. Its damage often comes from setting up several systems before the payoff, so avoid pressing major cooldowns with no preparation.", "Profano combina doenças, feridas, mascotes e gastos de Poder Rúnico. Seu dano muitas vezes vem de preparar vários sistemas antes da recompensa, então evite usar grandes recargas sem preparação.")
P("Festering Wounds", "Feridas Supurantes")
P("Build Festering Wounds on important targets and burst them with your wound-consuming attacks. Avoid creating far more wounds than you can realistically consume before the target dies.", "Crie Feridas Supurantes em alvos importantes e estoure-as com ataques que consomem feridas. Evite criar muito mais feridas do que conseguirá consumir antes de o alvo morrer.")
P("Pets and major cooldowns", "Mascotes e grandes recargas")
P("Dark Transformation, Apocalypse, and Army of the Dead reward planning. Use them when the target will live long enough for the summons and empowered pet time to matter.", "Transformação Negra, Apocalipse e Exército dos Mortos recompensam planejamento. Use quando o alvo viver tempo suficiente para que as invocações e o período de mascote fortalecido façam diferença.")
P("Runic Power", "Poder Rúnico")
P("Spend Runic Power without capping, but keep survival in mind in solo or PvP content. Death Coil and Epidemic are damage tools; Death Strike competes for the same resource when you need to live.", "Gaste Poder Rúnico sem atingir o limite, mas pense na sobrevivência em conteúdo solo ou JxJ. Espiral da Morte e Epidemia são ferramentas de dano; Golpe da Morte compete pelo mesmo recurso quando você precisa sobreviver.")
P("Content tips", "Dicas por conteúdo")
P("Delves / solo", "Imersões / solo")
P("Pull at a pace that lets you preserve Runic Power for recovery. Interrupt dangerous casts, use crowd control proactively, and do not save every defensive for an emergency that could have been prevented.", "Puxe em um ritmo que permita preservar Poder Rúnico para recuperação. Interrompa lançamentos perigosos, use controle de grupo de forma preventiva e não guarde todos os defensivos para uma emergência que poderia ter sido evitada.")
P("Dungeons", "Masmorras")
P("Your interrupt and grips are group utility. Learn which casts matter, use Anti-Magic Zone when several players will take magic damage, and coordinate large defensive cooldowns with dangerous pulls.", "Sua interrupção e seus puxões são utilidade para o grupo. Aprenda quais lançamentos importam, use Zona Antimagia quando vários jogadores receberem dano mágico e coordene grandes defensivos com pulls perigosos.")
P("Raids", "Raides")
P("Plan defensives around known mechanics instead of health percentage alone. Death's Advance can trivialize some forced-movement mechanics, and Anti-Magic Shell is strongest when used before predictable magic damage.", "Planeje defensivos em torno de mecânicas conhecidas, não apenas da porcentagem de vida. Avanço da Morte pode facilitar algumas mecânicas de movimento forçado, e Carapaça Antimagia é mais forte quando usada antes de dano mágico previsível.")
P("PvP", "JxJ")
P("Survival depends on predicting enemy cooldowns. Preserve Runic Power when you are likely to be targeted, use Anti-Magic Shell before incoming magic control, and use Icebound Fortitude during the enemy's real pressure window rather than after it ends.", "A sobrevivência depende de prever as recargas inimigas. Preserve Poder Rúnico quando você provavelmente será o alvo, use Carapaça Antimagia antes de controle mágico e use Fortitude Congélida durante a verdadeira janela de pressão inimiga, não depois que ela terminar.")
P("This guide is intentionally beginner-focused and complements the build source shown in the Loadouts tab. It does not replace encounter-specific guides or simulations.", "Este guia é propositalmente voltado para iniciantes e complementa a fonte de build mostrada na aba Loadouts. Ele não substitui guias específicos de encontros nem simulações.")

-- Chat/status strings frequently surfaced by the UI
P("Personal build code cleared for this profile.", "Código de build pessoal removido deste perfil.")
P("Personal build code saved locally for this profile.", "Código de build pessoal salvo localmente neste perfil.")
P("Created and saved WoW loadout '%s' for %s.", "Loadout do WoW '%s' criado e salvo para %s.")
P("A WoW talent loadout cannot be created while in combat. Try again after combat ends.", "Um loadout de talentos do WoW não pode ser criado durante o combate. Tente novamente após o combate.")
P("Using existing WoW loadout '%s' for %s.", "Usando o loadout existente do WoW '%s' para %s.")
P("This client could not create '%s'; bound the current WoW loadout '%s' instead.", "Este cliente não conseguiu criar '%s'; o loadout atual do WoW '%s' foi associado no lugar.")
P("Could not read or create a WoW talent loadout.", "Não foi possível ler ou criar um loadout de talentos do WoW.")
P("WoW cannot create another talent loadout for this specialization. Delete an unused loadout or bind an existing DKM loadout.", "O WoW não pode criar outro loadout de talentos para esta especialização. Apague um loadout não utilizado ou associe um loadout DKM existente.")
P("WoW rejected the new loadout request. Open the Talents window and try again out of combat.", "O WoW recusou a criação do novo loadout. Abra a janela de Talentos e tente novamente fora de combate.")
P("Creating WoW loadout '%s' from your current talent setup...", "Criando o loadout do WoW '%s' a partir dos talentos atuais...")
P("Saved WoW loadout cleared for this content type.", "Loadout salvo do WoW removido deste tipo de conteúdo.")
P("That WoW talent loadout is no longer available.", "Esse loadout de talentos do WoW não está mais disponível.")
P("Mapped WoW talent loadout '%s' to %s / %s.", "Loadout de talentos do WoW '%s' associado a %s / %s.")
P("Could not read the current WoW talent loadout.", "Não foi possível ler o loadout de talentos atual do WoW.")
P("Switching talents to '%s' for %s...", "Trocando talentos para '%s' em %s...")
P("Waiting for combat to end", "Aguardando o fim do combate")
P("WoW is not allowing talent changes right now", "O WoW não está permitindo alterações de talentos agora")
P("WoW rejected the talent loadout change", "O WoW recusou a troca do loadout de talentos")
P("Talent API call failed", "Falha na chamada da API de talentos")
P("Auto-switching to '%s' for %s.", "Trocando automaticamente para '%s' em %s.")
P("Could not switch talent loadout: %s", "Não foi possível trocar o loadout de talentos: %s")
P("That WoW equipment set is no longer available.", "Esse conjunto de equipamento do WoW não está mais disponível.")
P("Mapped equipment set '%s' to %s / %s.", "Conjunto de equipamento '%s' associado a %s / %s.")
P("More than one saved equipment set matches your current gear. Use 'Choose gear set...' to select one explicitly.", "Mais de um conjunto salvo corresponde ao equipamento atual. Use 'Escolher conjunto...' para selecionar um explicitamente.")
P("Your currently equipped gear does not exactly match a saved WoW equipment set. Equip one of your saved sets first or choose it from the list.", "O equipamento atual não corresponde exatamente a um conjunto salvo do WoW. Equipe um conjunto salvo primeiro ou escolha-o na lista.")
P("Created and saved equipment set '%s' for %s.", "Conjunto de equipamento '%s' criado e salvo para %s.")
P("Saved equipment-set association cleared for this content type. The WoW equipment set itself was not deleted.", "Associação do conjunto de equipamento removida deste conteúdo. O conjunto do WoW não foi apagado.")
P("Auto-equipping '%s' for %s.", "Equipando automaticamente '%s' para %s.")
P("Voice preview failed for %s: %s", "Falha na prévia de voz para %s: %s")
P("Lich King commentary preview played. Client locale: %s.", "Prévia dos comentários do Lich King reproduzida. Idioma do cliente: %s.")
P("Voice preview failed: %s", "Falha na prévia de voz: %s")
P("Invalid voice frequency. Use low, normal, or high.", "Frequência de voz inválida. Use low, normal ou high.")
P("Lich King commentary frequency set to %s.", "Frequência dos comentários do Lich King alterada para %s.")
P("Lich King commentary enabled.", "Comentários do Lich King ativados.")
P("Lich King commentary disabled.", "Comentários do Lich King desativados.")
P("Lich King commentary is allowed in PvP.", "Comentários do Lich King permitidos em JxJ.")
P("Lich King commentary is muted in PvP.", "Comentários do Lich King silenciados em JxJ.")
P("Use /dkm voice pvp on or /dkm voice pvp off.", "Use /dkm voice pvp on ou /dkm voice pvp off.")
P("Use /dkm voice on|off|test|low|normal|high|status|map|reset, /dkm voice pvp on|off, or /dkm voice situations on|off.", "Use /dkm voice on|off|test|low|normal|high|status|map|reset, /dkm voice pvp on|off ou /dkm voice situations on|off.")
P("Survival coach HUD enabled.", "HUD do Coach de sobrevivência ativado.")
P("Survival coach HUD disabled.", "HUD do Coach de sobrevivência desativado.")
P("Build HUD enabled.", "HUD de build ativado.")
P("Build HUD disabled.", "HUD de build desativado.")
P("Buff bar enabled.", "Barra de buffs ativada.")
P("Buff bar disabled.", "Barra de buffs desativada.")
P("Ability bar enabled.", "Barra de habilidades ativada.")
P("Ability bar disabled.", "Barra de habilidades desativada.")
P("Automatic equipment switching enabled.", "Troca automática de equipamento ativada.")
P("Automatic equipment switching disabled.", "Troca automática de equipamento desativada.")
P("Automatic talent switching enabled.", "Troca automática de talentos ativada.")
P("Automatic talent switching disabled.", "Troca automática de talentos desativada.")


P("Unavailable", "Indisponível")
P("Random (%d)", "Aleatória (%d)")
-- Header, build manager, combat status and diagnostics
P("Specialization: %s • Content: %s (%s)", "Especialização: %s • Conteúdo: %s (%s)")
P(" • War Mode active", " • Modo de Guerra ativo")
P("Build: %s", "Build: %s")
P("Guide: %s", "Guia: %s")
P("Build: not detected", "Build: não detectada")
P("Gear: not bound", "Equipamento: não associado")
P("Gear: %s", "Equipamento: %s")
P("Gear: saved set missing", "Equipamento: conjunto salvo ausente")
P("%s (%d missing)", "%s (%d ausente(s))")
P("DKM loadout:", "Loadout DKM:")
P("Gear:", "Equipamento:")
P(" • reviewed for %s on %s", " • revisado para %s em %s")
P(" • data package %s", " • pacote de dados %s")
P("PvP guide: %s", "Guia JxJ: %s")
P("Guide code: %s", "Código do guia: %s")
P("Source", "Fonte")
P("Build:", "Build:")
P("Gear:", "Equipamento:")
P("Equipment Set %s", "Conjunto de equipamento %s")
P("%s • locale: %s • PvP: %s • situations: %s%s", "%s • idioma: %s • JxJ: %s • situações: %s%s")
P(" • last: %s", " • última: %s")
P("(talent)", "(talento)")
P("Ability", "Habilidade")
P("USE", "USAR")
P("RP", "PR")
P("Frame positions and scale restored. HUD visibility settings were kept.", "Posições e escala das janelas restauradas. As configurações de visibilidade dos HUDs foram mantidas.")
P("Invalid mode. Use auto, world, delve, dungeon, raid, or pvp.", "Modo inválido. Use auto, world, delve, dungeon, raid ou pvp.")
P("Mode set to %s.", "Modo alterado para %s.")
P("Health-adaptive recommendations enabled.", "Recomendações adaptativas de vida ativadas.")
P("Health-adaptive recommendations disabled.", "Recomendações adaptativas de vida desativadas.")
P("This addon only runs on Death Knights.", "Este addon funciona apenas para Cavaleiros da Morte.")
P("Ready. Enable the native highlight, review your build focus, and use /dkm help to view commands.", "Pronto. Ative o destaque nativo, revise sua build e use /dkm help para ver os comandos.")
P("Situational Lich King comments enabled.", "Comentários situacionais do Lich King ativados.")
P("Situational Lich King comments disabled.", "Comentários situacionais do Lich King desativados.")
P("Voice mapping reset to Random.", "Mapeamento de vozes redefinido para Aleatória.")
P("All Lich King situation voices reset to Random.", "Todas as vozes situacionais do Lich King foram redefinidas para Aleatória.")

P("/dkm build choose — choose an existing WoW talent loadout for this content", "/dkm build choose — escolher um loadout de talentos existente para este conteúdo")
P("/dkm build current — bind the currently active WoW loadout", "/dkm build current — associar o loadout do WoW atualmente ativo")
P("/dkm build create — create a DKM copy from the current talents", "/dkm build create — criar uma cópia DKM a partir dos talentos atuais")

-- Action-bar coverage
P("The C_AssistedCombat API is not available in this game client.", "A API C_AssistedCombat não está disponível neste cliente do jogo.")
P("The native combat assistant could not be queried.", "Não foi possível consultar o assistente de combate nativo.")
P("Action bars: the native rotation has not provided a spell list yet.", "Barras de ação: a rotação nativa ainda não forneceu uma lista de habilidades.")
P("Action bars: %d/%d rotation spells found.", "Barras de ação: %d/%d habilidades da rotação encontradas.")
P("Action bars: %d/%d found. Missing or inside macros: %s%s", "Barras de ação: %d/%d encontradas. Ausentes ou dentro de macros: %s%s")
P(" Macro detection is approximate.", " A detecção de macros é aproximada.")
P("The native highlight could not be changed. Enable it in the WoW combat options.", "Não foi possível alterar o destaque nativo. Ative-o nas opções de combate do WoW.")

-- Beginner guide / HUD settings
P("Beginner guide for %s", "Guia para iniciantes — %s")
P("General Death Knight fundamentals", "Fundamentos gerais do Cavaleiro da Morte")
P("Current specialization", "Especialização atual")
P("Content: %s", "Conteúdo: %s")
P("Buff Bar", "Barra de Buffs")
P("Ability Availability", "Disponibilidade de Habilidades")
P("Build HUD", "HUD de Build")
P("Survival Coach", "Coach de Sobrevivência")
P("Shows important Death Knight buffs in a compact movable row.", "Mostra buffs importantes do Cavaleiro da Morte em uma barra compacta e móvel.")
P("Shows important abilities and whether they are ready, cooling down, or temporarily unusable.", "Mostra habilidades importantes e se estão prontas, em recarga ou temporariamente indisponíveis.")
P("Shows specialization, detected content, active build, and mapped gear.", "Mostra especialização, conteúdo detectado, build ativa e equipamento associado.")
P("Shows defensive and recovery recommendations, including health-adaptive priorities.", "Mostra recomendações defensivas e de recuperação, incluindo prioridades adaptadas à vida.")
P("Open the Guide tab for a beginner explanation of Death Knight resources, defensives, utility, and the current specialization.", "Abra a aba Guia para uma explicação para iniciantes sobre recursos, defensivos, utilidade e a especialização atual do Cavaleiro da Morte.")

-- New slash commands
P("/dkm — open or close the main window", "/dkm — abrir ou fechar a janela principal")
P("/dkm mode auto|world|delve|dungeon|raid|pvp", "/dkm mode auto|world|delve|dungeon|raid|pvp")
P("/dkm build — open Build Manager", "/dkm build — abrir a aba Loadouts")
P("/dkm build save — bind the current WoW loadout to this content", "/dkm build save — associar o loadout atual do WoW a este conteúdo")
P("/dkm build clear — clear the saved loadout for this content", "/dkm build clear — remover o loadout salvo deste conteúdo")
P("/dkm build auto on|off — auto-switch saved talent loadouts by content", "/dkm build auto on|off — trocar loadouts de talentos automaticamente por conteúdo")
P("/dkm gear choose — choose an existing WoW equipment set for this content", "/dkm gear choose — escolher um conjunto de equipamento do WoW para este conteúdo")
P("/dkm gear equipped — bind the currently equipped saved set", "/dkm gear equipped — associar o conjunto salvo atualmente equipado")
P("/dkm gear clear — clear the equipment-set association for this content", "/dkm gear clear — remover a associação de equipamento deste conteúdo")
P("/dkm gear auto on|off — auto-switch saved equipment sets by content", "/dkm gear auto on|off — trocar conjuntos de equipamento automaticamente por conteúdo")
P("/dkm coach on|off — show or hide the compact survival coach", "/dkm coach on|off — mostrar ou esconder o Coach de sobrevivência")
P("/dkm coach health on|off — toggle health-adaptive recommendations", "/dkm coach health on|off — ligar ou desligar recomendações adaptadas à vida")
P("/dkm hud on|off — show or hide the movable specialization/build HUD", "/dkm hud on|off — mostrar ou esconder o HUD móvel de especialização/build")
P("/dkm voice on|off|test|low|normal|high|status|map|reset", "/dkm voice on|off|test|low|normal|high|status|map|reset")
P("/dkm voice pvp on|off — allow or mute commentary in PvP", "/dkm voice pvp on|off — permitir ou silenciar comentários em JxJ")
P("/dkm voice situations on|off — toggle contextual spell/mount/hearthstone/AFK comments", "/dkm voice situations on|off — ligar ou desligar comentários de habilidades/montaria/pedra/AFK")
P("/dkm voice map — choose a voice per situation", "/dkm voice map — escolher uma voz para cada situação")
P("/dkm rotation — toggle the native offensive highlight", "/dkm rotation — ligar ou desligar o destaque ofensivo nativo")
P("/dkm bars — check native rotation spells on your action bars", "/dkm bars — verificar habilidades da rotação nativa nas barras")
P("/dkm reset — restore frame positions", "/dkm reset — restaurar posições das janelas")
P("/dkm guide — open the beginner specialization guide", "/dkm guide — abrir o guia da especialização para iniciantes")
P("/dkm settings — open HUD and commentary settings", "/dkm settings — abrir configurações de HUD e comentários")
P("/dkm buffs on|off — show or hide the movable buff bar", "/dkm buffs on|off — mostrar ou esconder a barra móvel de buffs")
P("/dkm abilities on|off — show or hide the ability availability bar", "/dkm abilities on|off — mostrar ou esconder a barra de disponibilidade de habilidades")
P("/dkm resources on|off — show or hide the Runes + Runic Power HUD", "/dkm resources on|off — mostrar ou esconder o HUD de Runas + Poder Rúnico")
P("/dkm resources runes on|off — show or hide Rune segments", "/dkm resources runes on|off — mostrar ou esconder os segmentos de Runas")
P("/dkm resources power on|off — show or hide Runic Power", "/dkm resources power on|off — mostrar ou esconder o Poder Rúnico")

-- Equipment/status selector strings
P("Map an existing WoW Equipment Set to %s / %s. This mapping is used by Gear AUTO.", "Associe um conjunto de equipamento existente do WoW a %s / %s. Essa associação é usada pelo Equipamento AUTO.")
P("No saved WoW Equipment Sets were found. Create one in the Character > Equipment Manager first.", "Nenhum conjunto de equipamento salvo do WoW foi encontrado. Crie um primeiro em Personagem > Gerenciador de Equipamentos.")
P("Click a saved WoW set to map it. DK Mentor does not duplicate it.", "Clique em um conjunto salvo do WoW para associá-lo. O DK Mentor não o duplica.")

-- v0.6.0 navigation and usability
P("Loadouts", "Loadouts")
P("Combat profile:", "Perfil de combate:")
P("Detected content:", "Conteúdo detectado:")
P("Configure loadout for:", "Configurar loadout para:")
P("HUD visibility is configured in Settings", "A visibilidade do HUD é configurada em Configurações")
P("This guide follows your current Death Knight specialization only. It is not tied to the World/Delve/Dungeon/Raid/PvP loadout profile.", "Este guia acompanha apenas a especialização atual do Cavaleiro da Morte. Ele não depende do perfil de loadout de Mundo/Imersão/Masmorra/Raide/JxJ.")
P("Global addon settings. These options apply across all Death Knight specializations and content profiles.", "Configurações globais do addon. Estas opções valem para todas as especializações do Cavaleiro da Morte e todos os perfis de conteúdo.")
P("HUDs and layout", "HUDs e layout")
P("Choose which combat HUDs are visible. Unlock them only while arranging the interface, then lock them again to prevent accidental dragging.", "Escolha quais HUDs de combate ficam visíveis. Desbloqueie apenas enquanto organiza a interface e depois bloqueie novamente para evitar movimentos acidentais.")
P("Automatic switching", "Troca automática")
P("Loadout mappings are configured per specialization and content in the Loadouts tab. These switches are global.", "As associações de loadout são configuradas por especialização e conteúdo na aba Loadouts. Estes controles são globais.")
P("Talent loadout", "Loadout de talentos")
P("Equipment set", "Conjunto de equipamento")
P("Mapped", "Associado")
P("This mapping is specific to %s / %s. Automatic talent and equipment switching are global options in Settings.", "Esta associação é específica para %s / %s. A troca automática de talentos e equipamento é uma opção global em Configurações.")
P("This mapping is specific to %s / %s. DK Mentor detects the environment automatically and switches to the mapped talents and equipment when Talents AUTO / Gear AUTO are enabled in Settings.", "Esta associação é específica para %s / %s. O DK Mentor detecta o ambiente automaticamente e troca para os talentos e equipamentos mapeados quando Talentos AUTO / Equipamento AUTO estão ligados em Configurações.")
P("Loadouts — %s / %s", "Loadouts — %s / %s")
P("Survival — %s / %s", "Sobrevivência — %s / %s")
P("Beginner guide — %s", "Guia para iniciantes — %s")
P("HUDs: LOCKED", "HUDs: BLOQUEADOS")
P("HUDs: UNLOCKED", "HUDs: DESBLOQUEADOS")
P("Preview HUDs: ON", "Prévia dos HUDs: LIGADA")
P("Preview HUDs: OFF", "Prévia dos HUDs: DESLIGADA")
P("Bar size...", "Tamanho das barras...")
P("HUD size...", "Tamanho dos HUDs...")
P("Combat bar size and layout", "Tamanho e layout das barras de combate")
P("Combat HUD size and layout", "Tamanho e layout dos HUDs de combate")
P("Adjust each combat bar independently. Size scales the whole HUD; icons per row changes its width before wrapping. Preview HUDs always overrides combat-only visibility while you arrange the interface.", "Ajuste cada barra de combate separadamente. Tamanho escala todo o HUD; ícones por linha altera a largura antes da quebra de linha. A Prévia dos HUDs sempre ignora a opção de exibir só em combate enquanto você organiza a interface.")
P("Adjust each combat HUD independently. Size scales the whole HUD; aura/ability rows can change width, and the DK Resources row can switch between Runes, Runic Power, or both. Preview HUDs overrides combat-only visibility while you arrange the interface.", "Ajuste cada HUD de combate separadamente. O tamanho escala todo o HUD; as barras de aura/habilidades podem mudar de largura e o HUD de Recursos do DK pode exibir Runas, Poder Rúnico ou ambos. A Prévia dos HUDs ignora a opção de exibir só em combate enquanto você organiza a interface.")
P("Bar", "Barra")
P("Size", "Tamanho")
P("Icons per row", "Ícones por linha")
P("Icons / mode", "Ícones / modo")
P("Runes + Runic Power", "Runas + Poder Rúnico")
P("ON", "LIGADO")
P("OFF", "DESLIGADO")
P("Opacity", "Opacidade")
P("HUD appearance...", "Aparência dos HUDs...")
P("Adjust each combat HUD independently. Size scales the whole HUD, opacity controls transparency, aura/ability rows can change width, and DK Resources has its own text and Rune-spacing options. Preview HUDs overrides combat-only visibility while you arrange the interface.", "Ajuste cada HUD de combate separadamente. O tamanho escala todo o HUD, a opacidade controla a transparência, as barras de aura/habilidades podem mudar de largura e os Recursos do DK possuem opções próprias de texto e espaçamento das Runas. A Prévia dos HUDs ignora a opção de exibir só em combate enquanto você organiza a interface.")
P("DK Resources appearance", "Aparência dos Recursos do DK")
P("Adjust each combat HUD independently. Size scales the whole HUD, opacity controls transparency, aura/ability rows can change width, and DK Resources has its own mode, style, text, Rune spacing, and Arc opening. Preview HUDs overrides combat-only visibility while you arrange the interface.", "Ajuste cada HUD de combate separadamente. O tamanho escala todo o HUD, a opacidade controla a transparência, as barras de aura/habilidades podem mudar de largura e os Recursos do DK possuem modo, estilo, texto, espaçamento das Runas e abertura dos arcos. A Prévia dos HUDs ignora a opção de exibir só em combate enquanto você organiza a interface.")
P("Arc opening", "Abertura dos arcos")
P("Close or open the two arcs around the character without changing their size.", "Feche ou abra os dois arcos ao redor do personagem sem alterar o tamanho deles.")
P("Current DK Resources: %s • Style %s • Size %d%% • Opacity %d%% • Arc opening %s", "Recursos do DK atuais: %s • Estilo %s • Tamanho %d%% • Opacidade %d%% • Abertura %s")
P("Power text: ON", "Texto do Poder: LIGADO")
P("Power text: OFF", "Texto do Poder: DESLIGADO")
P("Rune spacing: %s", "Espaçamento das Runas: %s")
P("Compact", "Compacto")
P("Wide", "Amplo")
P("Restore DK Resources", "Restaurar Recursos do DK")
P("Restore HUD appearance", "Restaurar aparência dos HUDs")
P("Current DK Resources: %s • Size %d%% • Opacity %d%%", "Recursos do DK atuais: %s • Tamanho %d%% • Opacidade %d%%")
P("Resources: %s • Text: %s • Rune spacing: %s", "Recursos: %s • Texto: %s • Espaçamento: %s")
P("HUD size and opacity restored to defaults.", "Tamanho e opacidade dos HUDs restaurados para o padrão.")
P("DK Resources HUD restored to defaults.", "HUD de Recursos do DK restaurado para o padrão.")
P("Runes only", "Só Runas")
P("Runic Power only", "Só Poder Rúnico")
P("Resources hidden", "Recursos ocultos")
P("Restore default sizes", "Restaurar tamanhos padrão")
P("Close", "Fechar")
P("Bar layout cannot be changed during combat.", "O tamanho e o layout das barras não podem ser alterados durante o combate.")
P("HUD preview cannot be changed during combat.", "A prévia dos HUDs não pode ser alterada durante o combate.")
P("HUD positions cannot be changed during combat.", "As posições dos HUDs não podem ser alteradas durante o combate.")
P("Combat bar sizes restored to defaults.", "Os tamanhos das barras de combate foram restaurados para o padrão.")
P("Reset HUD positions", "Restaurar posições dos HUDs")
P("Locked — unlock HUDs in Settings", "Bloqueado — desbloqueie os HUDs em Configurações")
P("HUDs are locked. Unlock them in Settings to move this panel.", "Os HUDs estão bloqueados. Desbloqueie em Configurações para mover este painel.")
P("Combat HUDs locked.", "HUDs de combate bloqueados.")
P("Combat HUDs unlocked. Drag them to arrange the interface.", "HUDs de combate desbloqueados. Arraste-os para organizar a interface.")
P("Shows all six Runes plus Runic Power in a compact movable Death Knight resource HUD.", "Mostra as seis Runas e o Poder Rúnico em um HUD compacto e móvel de recursos do Cavaleiro da Morte.")
P("Tracks all six Death Knight Runes and Runic Power in one compact HUD.", "Monitora as seis Runas do Cavaleiro da Morte e o Poder Rúnico em um único HUD compacto.")
P("Runes fill as they recharge. Runic Power uses Blizzard's native StatusBar so primary-power secret values can be displayed safely during combat.", "As Runas vão preenchendo conforme recarregam. O Poder Rúnico usa a StatusBar nativa da Blizzard para exibir com segurança valores primários secretos durante o combate.")
P("DK resource HUD enabled.", "HUD de recursos do DK ativado.")
P("DK resource HUD disabled.", "HUD de recursos do DK desativado.")
P("/dkm hud lock|unlock|preview — arrange combat HUDs", "/dkm hud lock|unlock|preview — organizar os HUDs de combate")
P("Combat HUD positions restored.", "Posições dos HUDs de combate restauradas.")
P("Aura/ability bars: COMBAT ONLY", "Barras de aura/habilidades: SÓ EM COMBATE")
P("Aura/ability bars: ALWAYS", "Barras de aura/habilidades: SEMPRE")
P("Bars only in combat: ON", "Barras só em combate: LIGADO")
P("Bars only in combat: OFF", "Barras só em combate: DESLIGADO")
P("Aura and ability bars now show only in combat.", "As barras de aura e habilidades agora aparecem apenas em combate.")
P("Aura and ability bars can now show outside combat.", "As barras de aura e habilidades agora também podem aparecer fora de combate.")
P("Combat bars and resources now show only in combat.", "As barras e os recursos de combate agora aparecem apenas em combate.")
P("Combat bars and resources can now show outside combat.", "As barras e os recursos de combate agora também podem aparecer fora de combate.")
P("/dkm combatbars combat|always - control aura/ability bar visibility", "/dkm combatbars combat|always - controlar a visibilidade das barras de aura/habilidades")
P("/dkm combatbars combat|always - show aura/ability bars only in combat or always", "/dkm combatbars combat|always - mostrar as barras de aura/habilidades apenas em combate ou sempre")

-- Addon language
P("Language", "Idioma")
P("Addon language", "Idioma do addon")
P("Choose language...", "Escolher idioma...")
P("Choose the DK Mentor language. Automatic follows the WoW client language; unsupported client languages use English.", "Escolha o idioma do DK Mentor. Automático segue o idioma do cliente do WoW; idiomas ainda não traduzidos usam inglês.")
P("Automatic (WoW)", "Automático (WoW)")
P("Portuguese (Brazil)", "Português (Brasil)")
P("English", "English")
P("Current: %s", "Atual: %s")
P("Language: %s", "Idioma: %s")
P("Language changed to %s. Reloading the interface...", "Idioma alterado para %s. Recarregando a interface...")
P("Language saved as %s. Use /reload to apply it after combat.", "Idioma salvo como %s. Use /reload para aplicar após o combate.")
P("Language saved as %s. Type /reload to apply it.", "Idioma salvo como %s. Digite /reload para aplicar.")
P("Cancel", "Cancelar")
P("/dkm language auto|ptbr|en — change DK Mentor language", "/dkm language auto|ptbr|en — alterar o idioma do DK Mentor")

function DKM.T(key, ...)
    key = tostring(key or "")
    local value = key
    if locale == "ptBR" then
        value = ptBR[key] or key
    end
    if select("#", ...) > 0 then
        local ok, formatted = pcall(string.format, value, ...)
        if ok then
            return formatted
        end
    end
    return value
end

P("Mythic+", "Mítica+")
P("Playing specialization", "Especialização de jogo")
P("Loot specialization", "Especialização de saque")
P("No override", "Sem override")
P("Current specialization (%s)", "Especialização atual (%s)")
P("Loot: %s", "Saque: %s")
P("Spec: %s • Loot: %s • Talents: %s • Gear: %s", "Spec: %s • Saque: %s • Talentos: %s • Equip.: %s")
P("Uses Dungeon/Mythic+ profile", "Usa o perfil de Masmorra/Mítica+")
P("Spec: Use %s default", "Spec: Usar padrão de %s")
P("Talents: Use %s default", "Talentos: Usar padrão de %s")
P("Gear: Use %s default", "Equip.: Usar padrão de %s")
P("One override per dungeon is shared across Normal, Heroic, Mythic 0, and Mythic+. Spec, talents, and gear can inherit the active Dungeon/Mythic+ profile; Loot Spec is independent.", "Um override por masmorra é compartilhado entre Normal, Heroica, Mítica 0 e Mítica+. Spec, talentos e equipamento podem herdar o perfil ativo de Masmorra/Mítica+; a especialização de saque é independente.")
P("One dungeon rule is reused across Normal, Heroic, Mythic 0, and Mythic+. Inherited fields follow the active Dungeon/Mythic+ profile.", "Uma regra de masmorra é reutilizada em Normal, Heroica, Mítica 0 e Mítica+. Campos herdados seguem o perfil ativo de Masmorra/Mítica+.")
P("Changes only the loot table preference; it never changes the role you are playing.", "Altera apenas a preferência da tabela de saque; nunca muda o papel que você está jogando.")
P("Inherit follows the active Dungeon or Mythic+ profile. Keep current prevents DK Mentor from changing that component. Loot Spec uses No override when DK Mentor should leave it alone.", "Herdar segue o perfil ativo de Masmorra ou Mítica+. Manter atual impede o DK Mentor de alterar aquele componente. Em Saque, use Sem override quando o DK Mentor não deve alterar nada.")
P("Loot specialization is unavailable on this client.", "A especialização de saque não está disponível neste cliente.")
P("WoW did not allow the loot specialization change yet.", "O WoW ainda não permitiu a troca da especialização de saque.")
P("Applying loot specialization...", "Aplicando especialização de saque...")
P("Loot specialization changed to %s.", "Especialização de saque alterada para %s.")
P("Loot specialization restored to %s.", "Especialização de saque restaurada para %s.")
P("Loadout status", "Status do loadout")
P("Content: %s", "Conteúdo: %s")
P("Dungeon: %s", "Masmorra: %s")
P("Current specialization: %s (%s)", "Especialização atual: %s (%s)")
P("Target specialization: %s", "Especialização alvo: %s")
P("Assigned group role: %s", "Papel atribuído no grupo: %s")
P("Loot specialization: %s", "Especialização de saque: %s")
P("Dungeon override: ACTIVE", "Override de masmorra: ATIVO")
P("This profile is specific to %s / %s. DK Mentor can switch specialization, talents, and equipment automatically when their AUTO options are enabled. Dungeon overrides can also set Loot Spec independently.", "Este perfil é específico para %s / %s. O DK Mentor pode trocar especialização, talentos e equipamento automaticamente quando as opções AUTO estiverem ligadas. Overrides de masmorra também podem definir a especialização de saque de forma independente.")

function DKM.SetLocaleOverride(value)
    locale, localeOverride = ResolveEffectiveLocale(value)
    DKM.locale = locale
    DKM.rawLocale = clientLocale
    DKM.languageOverride = localeOverride
    return locale
end

function DKM.GetLocaleOverride()
    return localeOverride
end

function DKM.GetClientLocale()
    return clientLocale
end

DKM.SetLocaleOverride(localeOverride)

P("Shows helpful effects on you that were applied by other players or NPCs.", "Mostra efeitos positivos em você que foram aplicados por outros jogadores ou NPCs.")
P("Shows harmful effects currently affecting your character.", "Mostra efeitos negativos que estão afetando seu personagem no momento.")
P("External buff bar enabled.", "Barra de buffs externos ativada.")
P("External buff bar disabled.", "Barra de buffs externos desativada.")
P("Debuff bar enabled.", "Barra de debuffs ativada.")
P("Debuff bar disabled.", "Barra de debuffs desativada.")
P("/dkm buffs on|off — show or hide the movable DK buff bar", "/dkm buffs on|off — mostrar ou ocultar a barra móvel de buffs do DK")
P("/dkm externalbuffs on|off — show or hide buffs received from others", "/dkm externalbuffs on|off — mostrar ou ocultar buffs recebidos de outros")
P("/dkm debuffs on|off — show or hide harmful effects on yourself", "/dkm debuffs on|off — mostrar ou ocultar efeitos negativos em você")

P("Content detection is automatic. DK Mentor follows the current game environment.", "A detecção de conteúdo é automática. O DK Mentor acompanha o ambiente atual do jogo.")

-- 1.0.11 proc tracking and interrupt alert
P("Interrupt alert: ON", "Alerta de interrupção: LIGADO")
P("Interrupt alert: OFF", "Alerta de interrupção: DESLIGADO")
P("Interrupt alert enabled.", "Alerta de interrupção ativado.")
P("Interrupt alert disabled.", "Alerta de interrupção desativado.")
P("Shows the Mind Freeze icon only when your current target has a confirmed interruptible cast or channel.", "Mostra o ícone de Congelar Mente somente quando seu alvo atual estiver lançando ou canalizando algo confirmado como interrompível.")
P("Appears when your current target is confirmed to be casting or channeling an interruptible spell.", "Aparece quando seu alvo atual estiver lançando ou canalizando uma magia confirmada como interrompível.")
P("/dkm interrupt on|off — show or hide the Mind Freeze interrupt alert", "/dkm interrupt on|off — exibe ou oculta o alerta de Congelar Mente")

P("Active DK procs are prioritized first and mirrored from Blizzard tracked buffs when available.", "Procs ativos do DK têm prioridade e são espelhados dos buffs rastreados da Blizzard quando disponíveis.")

-- 1.1.2 DK Arcs / IceHUD-inspired resource layout
P("DK Arcs", "Arcos do DK")
P("Classic", "Clássico")
P("Style: %s", "Estilo: %s")
P("Drag", "Mover")
P("DK-focused side HUD inspired by IceHUD: Health on the left, Runic Power on the right, and six Runes centered below.", "HUD lateral focado em DK e inspirado no IceHUD: Vida à esquerda, Poder Rúnico à direita e seis Runas centralizadas abaixo.")
P("/dkm resources style classic|arcs — choose the DK Resources visual style", "/dkm resources style classic|arcs — escolher o estilo visual dos Recursos do DK")

-- 1.2.0 Loadouts 2.0
P("Click to choose Blood, Frost, or Unholy manually. Automatic specialization switching can be configured in Loadouts.", "Clique para escolher Sangue, Gélido ou Profano manualmente. A troca automática de especialização pode ser configurada em Loadouts.")
P("Profile specialization", "Especialização do perfil")
P("Profile spec:", "Spec do perfil:")
P("Do not change", "Não alterar")
P("Do not change (%s)", "Não alterar (%s)")
P("SELECTED", "SELECIONADO")
P("Specialization", "Especialização")
P("Specialization: %s", "Especialização: %s")
P("Specialization: keep current (%s)", "Especialização: manter atual (%s)")
P("Expected specialization: %s", "Especialização esperada: %s")
P("Waiting for specialization: %s", "Aguardando especialização: %s")
P("Talent loadout after specialization change: %s", "Loadout de talentos após trocar de especialização: %s")
P("SPEC", "SPEC")
P("Spec AUTO: ON", "Spec AUTO: LIGADO")
P("Spec AUTO: OFF", "Spec AUTO: DESLIGADO")
P("Automatic specialization switching enabled.", "Troca automática de especialização ativada.")
P("Automatic specialization switching disabled.", "Troca automática de especialização desativada.")
P("The target specialization is not available.", "A especialização de destino não está disponível.")
P("WoW did not allow the automatic specialization change.", "O WoW não permitiu a troca automática de especialização.")
P("Auto-switching specialization to %s for %s...", "Trocando automaticamente a especialização para %s em %s...")
P("Tank", "Tank")
P("Damage", "DPS")
P("Healer", "Healer")
P("Role protection: your group role is %s, but the target specialization is %s (%s). Automatic specialization switching was skipped.", "Proteção de função: sua função no grupo é %s, mas a especialização de destino é %s (%s). A troca automática de especialização foi ignorada.")
P("Role protection: switching from %s to %s would change your group role from %s to %s. Automatic specialization switching was skipped.", "Proteção de função: trocar de %s para %s mudaria sua função no grupo de %s para %s. A troca automática de especialização foi ignorada.")
P("Uses Dungeon profile", "Usa o perfil de Masmorra")
P("Override disabled", "Override desativado")
P("Keep current", "Manter atual")
P("Dungeon default", "Padrão de Masmorra")
P("Custom", "Personalizado")
P("Spec: %s • Talents: %s • Gear: %s", "Spec: %s • Talentos: %s • Equipamento: %s")
P("Dungeon overrides...", "Overrides de masmorra...")
P("Dungeon Overrides", "Overrides de Masmorra")
P("Dungeon override", "Override de masmorra")
P("Current dungeon", "Masmorra atual")
P("Override specialization, talents, or gear for individual dungeons. Anything left on Dungeon default inherits your normal Dungeon profile.", "Sobrescreva especialização, talentos ou equipamento por masmorra. Tudo que ficar em Padrão de Masmorra herda o perfil normal de Masmorra.")
P("Configure", "Configurar")
P("No dungeons were discovered yet. Enter a dungeon or open the Mythic+ interface, then reopen this window.", "Nenhuma masmorra foi descoberta ainda. Entre em uma masmorra ou abra a interface de Mítica+ e depois reabra esta janela.")
P("Showing %d-%d of %d dungeons • use the mouse wheel to scroll.", "Exibindo %d-%d de %d masmorras • use a roda do mouse para rolar.")
P("%d dungeons discovered dynamically from WoW and your visited instances.", "%d masmorras descobertas dinamicamente pelo WoW e pelas instâncias visitadas.")
P("Override: DISABLED", "Override: DESLIGADO")
P("Override: ENABLED", "Override: LIGADO")
P("Spec: Keep current", "Spec: Manter atual")
P("Spec: Use Dungeon default", "Spec: Usar padrão de Masmorra")
P("Effective specialization for talent selection: %s", "Especialização efetiva para selecionar talentos: %s")
P("Talents: Keep current", "Talentos: Manter atuais")
P("Talents: %s", "Talentos: %s")
P("Talents: Use Dungeon default", "Talentos: Usar padrão de Masmorra")
P("Gear: Keep current", "Equipamento: Manter atual")
P("Gear: Use Dungeon default", "Equipamento: Usar padrão de Masmorra")
P("Inherit keeps the normal Dungeon profile. Keep current prevents DK Mentor from changing only that component. Choosing an explicit value overrides only that component.", "Herdar mantém o perfil normal de Masmorra. Manter atual impede o DK Mentor de trocar apenas aquele componente. Escolher um valor explícito sobrescreve somente aquele componente.")
P("Delete override", "Excluir override")
P("Done", "Concluir")
P("Dungeon Override — %s", "Override de Masmorra — %s")
P("This override is matched by WoW dungeon IDs discovered at runtime; it does not depend on a hardcoded season list.", "Este override usa IDs de masmorra do WoW descobertos em tempo de execução; ele não depende de uma lista de temporada fixa no addon.")
P("Dungeon override talent loadout set to '%s' (%s).", "Loadout de talentos do override de masmorra definido como '%s' (%s).")
P("Switch to %s before using the current talent loadout for this override.", "Troque para %s antes de usar o loadout de talentos atual neste override.")
P("Dungeon override equipment set set to '%s'.", "Conjunto de equipamento do override de masmorra definido como '%s'.")
P("More than one saved equipment set matches your current gear. Choose one explicitly.", "Mais de um conjunto salvo corresponde ao equipamento atual. Escolha um explicitamente.")
P("Your currently equipped gear does not exactly match a saved WoW equipment set.", "Seu equipamento atual não corresponde exatamente a um conjunto de equipamento salvo no WoW.")
P("Choose a WoW talent loadout for the %s override (%s).", "Escolha um loadout de talentos do WoW para o override de %s (%s).")
P("Choosing a loadout overrides only talents for this dungeon. Other values can still inherit the Dungeon profile.", "Escolher um loadout sobrescreve apenas os talentos desta masmorra. Os outros valores ainda podem herdar o perfil de Masmorra.")
P("Choose a WoW Equipment Set for the %s override (%s).", "Escolha um Conjunto de Equipamento do WoW para o override de %s (%s).")
P("Choosing a set overrides only gear for this dungeon. Other values can still inherit the Dungeon profile.", "Escolher um conjunto sobrescreve apenas o equipamento desta masmorra. Os outros valores ainda podem herdar o perfil de Masmorra.")
P("Dungeon override: keep current talents", "Override de masmorra: manter talentos atuais")
P("Dungeon override: keep current gear", "Override de masmorra: manter equipamento atual")
P("Build: current", "Build: atual")
P("Gear: current", "Equipamento: atual")
P("Specialization, talent, and gear mappings are configured per content profile in the Loadouts tab. These switches are global.", "Especialização, talentos e equipamento são configurados por perfil de conteúdo na aba Loadouts. Estes controles AUTO são globais.")
P("This profile is specific to %s / %s. DK Mentor can switch specialization, talents, and equipment automatically when their AUTO options are enabled. Dungeon overrides can replace only the values you choose.", "Este perfil é específico para %s / %s. O DK Mentor pode trocar especialização, talentos e equipamento automaticamente quando as opções AUTO estiverem ligadas. Overrides de masmorra substituem apenas os valores que você escolher.")
