local ADDON_NAME, DKM = ...

-- DK Meta Pulse snapshot.
--
-- Archon.gg is used here as observed Warcraft Logs-derived meta data, not as a
-- replacement for DK Mentor's guide-backed recommendations. The addon never
-- performs live web requests. This file is reviewed and versioned with DK Mentor.
-- Popularity is observational: it can reflect availability, encounter mix, and
-- player behavior, so it should not be interpreted as automatic BiS or a command
-- to switch specialization.
local MetaData = {
    patch = "12.1.0",
    season = "Midnight Season 2",
    reviewed = "2026-09-08",
    sourceName = "Archon.gg / Warcraft Logs",
    heroSpellIDs = {
        ["Deathbringer"] = 434765,
        ["San'layn"] = 433895,
        ["Rider of the Apocalypse"] = 444040,
    },
    sourceMethod = "Observed build usage from the last 14 days. Raid uses Heroic All Bosses; Mythic+ uses all +7 and above; High Keys uses the top 5% of keys.",
    disclaimer = "Observed popularity is not the same as theoretical best. Gear availability, encounter mix, sample size, and player skill can bias the data. Use DK Mentor guide recommendations for the why, Archon for the observed what, and simulate character-specific gear when choices are close.",
    contextOrder = { "raid", "mythicplus", "highkeys" },
    contexts = {
        raid = {
            label = "Heroic Raid",
            short = "Heroic • All Bosses • top 50% sample • last 14 days",
            advice = "For Raid DPS, Frost has the clearest Hero Talent consensus in this snapshot. Unholy remains viable, but its Rider/San'layn split is much closer. Blood is shown separately as the DK tank signal, not compared directly with DPS specs.",
            specs = {
                [250] = {
                    role = "Tank",
                    signal = "STRONG CONSENSUS",
                    hero = "San'layn",
                    heroSpellID = 433895,
                    heroUsage = 91.5,
                    alternativeHero = "Deathbringer",
                    alternativeHeroSpellID = 434765,
                    alternativeUsage = 8.4,
                    parses = 103847,
                    buildDps = 130300,
                    popularWeapon = "Blood Knight's Warblade",
                    weaponUsage = 57.7,
                    sourceURL = "https://www.archon.gg/wow/builds/blood/death-knight/raid/talents/heroic/all-bosses",
                    gearURL = "https://www.archon.gg/wow/builds/blood/death-knight/raid/gear-and-tier-set/heroic/all-bosses",
                },
                [251] = {
                    role = "DPS",
                    signal = "VERY STRONG CONSENSUS",
                    hero = "Deathbringer",
                    heroSpellID = 434765,
                    heroUsage = 96.8,
                    alternativeHero = "Rider of the Apocalypse",
                    alternativeHeroSpellID = 444040,
                    alternativeUsage = 3.2,
                    parses = 40059,
                    buildDps = 229400,
                    popularWeapon = "Spellbreaker's Blade",
                    weaponUsage = 42.5,
                    sourceURL = "https://www.archon.gg/wow/builds/frost/death-knight/raid/talents/heroic/all-bosses",
                    gearURL = "https://www.archon.gg/wow/builds/frost/death-knight/raid/gear-and-tier-set/heroic/all-bosses",
                },
                [252] = {
                    role = "DPS",
                    signal = "SPLIT META",
                    hero = "Rider of the Apocalypse",
                    heroSpellID = 444040,
                    heroUsage = 54.2,
                    alternativeHero = "San'layn",
                    alternativeHeroSpellID = 433895,
                    alternativeUsage = 45.7,
                    parses = 100402,
                    buildDps = 207900,
                    popularWeapon = "Blood Knight's Warblade",
                    weaponUsage = 61.6,
                    sourceURL = "https://www.archon.gg/wow/builds/unholy/death-knight/raid/talents/heroic/all-bosses",
                    gearURL = "https://www.archon.gg/wow/builds/unholy/death-knight/raid/gear-and-tier-set/heroic/all-bosses",
                },
            },
        },
        mythicplus = {
            label = "Mythic+ +7 to +20",
            short = "+7 to +20 • All Dungeons • last 14 days",
            advice = "For general Mythic+, Frost currently has the cleaner and more consolidated DPS meta signal. Unholy is almost evenly split between San'layn and Rider, so both styles remain common. Blood is evaluated independently as the DK tank option.",
            specs = {
                [250] = {
                    role = "Tank",
                    signal = "STRONG CONSENSUS",
                    hero = "San'layn",
                    heroSpellID = 433895,
                    heroUsage = 87.9,
                    alternativeHero = "Deathbringer",
                    alternativeHeroSpellID = 434765,
                    alternativeUsage = 12.1,
                    parses = 514692,
                    maxKey = 21,
                    buildDps = 193800,
                    popularWeapon = "Blood Knight's Warblade",
                    weaponUsage = 53.5,
                    sourceURL = "https://www.archon.gg/wow/builds/blood/death-knight/mythic-plus/talents/10/all-dungeons/this-week",
                    gearURL = "https://www.archon.gg/wow/builds/blood/death-knight/mythic-plus/gear-and-tier-set/10/all-dungeons/this-week",
                },
                [251] = {
                    role = "DPS",
                    signal = "VERY STRONG CONSENSUS",
                    hero = "Deathbringer",
                    heroSpellID = 434765,
                    heroUsage = 97.4,
                    alternativeHero = "Rider of the Apocalypse",
                    alternativeHeroSpellID = 444040,
                    alternativeUsage = 2.6,
                    parses = 61176,
                    maxKey = 20,
                    buildDps = 281600,
                    popularWeapon = "Spellbreaker's Blade",
                    weaponUsage = 42.9,
                    sourceURL = "https://www.archon.gg/wow/builds/frost/death-knight/mythic-plus/talents/10/all-dungeons/this-week",
                    gearURL = "https://www.archon.gg/wow/builds/frost/death-knight/mythic-plus/gear-and-tier-set/10/all-dungeons/this-week",
                },
                [252] = {
                    role = "DPS",
                    signal = "SPLIT META",
                    hero = "San'layn",
                    heroSpellID = 433895,
                    heroUsage = 53.3,
                    alternativeHero = "Rider of the Apocalypse",
                    alternativeHeroSpellID = 444040,
                    alternativeUsage = 46.6,
                    parses = 130897,
                    maxKey = 18,
                    buildDps = 263000,
                    popularWeapon = "Blood Knight's Warblade",
                    weaponUsage = 52.2,
                    sourceURL = "https://www.archon.gg/wow/builds/unholy/death-knight/mythic-plus/talents/10/all-dungeons/this-week",
                    gearURL = "https://www.archon.gg/wow/builds/unholy/death-knight/mythic-plus/gear-and-tier-set/10/all-dungeons/this-week",
                },
            },
        },
        highkeys = {
            label = "High Keys",
            short = "Top 5% of keys • All Dungeons • last 14 days",
            advice = "In High Keys, both Frost and Unholy have established DPS patterns: Frost is almost universally Deathbringer, while Unholy shifts strongly toward San'layn. Blood is also overwhelmingly San'layn among the observed top-key sample. Treat this as a push-meta signal, not a requirement for ordinary keys.",
            specs = {
                [250] = {
                    role = "Tank",
                    signal = "VERY STRONG CONSENSUS",
                    hero = "San'layn",
                    heroSpellID = 433895,
                    heroUsage = 98.5,
                    alternativeHero = "Deathbringer",
                    alternativeHeroSpellID = 434765,
                    alternativeUsage = 1.5,
                    parses = 26716,
                    maxKey = 21,
                    buildDps = 236100,
                    popularWeapon = "Blood Knight's Warblade",
                    weaponUsage = 68.4,
                    sourceURL = "https://www.archon.gg/wow/builds/blood/death-knight/mythic-plus/talents/high-keys/all-dungeons/this-week",
                    gearURL = "https://www.archon.gg/wow/builds/blood/death-knight/mythic-plus/gear-and-tier-set/high-keys/all-dungeons/this-week",
                },
                [251] = {
                    role = "DPS",
                    signal = "VERY STRONG CONSENSUS",
                    hero = "Deathbringer",
                    heroSpellID = 434765,
                    heroUsage = 99.5,
                    alternativeHero = "Rider of the Apocalypse",
                    alternativeHeroSpellID = 444040,
                    alternativeUsage = 0.5,
                    parses = 3261,
                    maxKey = 20,
                    buildDps = 339100,
                    popularWeapon = "Spellbreaker's Blade",
                    weaponUsage = 48.9,
                    sourceURL = "https://www.archon.gg/wow/builds/frost/death-knight/mythic-plus/talents/high-keys/all-dungeons/this-week",
                    gearURL = "https://www.archon.gg/wow/builds/frost/death-knight/mythic-plus/gear-and-tier-set/high-keys/all-dungeons/this-week",
                },
                [252] = {
                    role = "DPS",
                    signal = "STRONG CONSENSUS",
                    hero = "San'layn",
                    heroSpellID = 433895,
                    heroUsage = 80.9,
                    alternativeHero = "Rider of the Apocalypse",
                    alternativeHeroSpellID = 444040,
                    alternativeUsage = 19.1,
                    parses = 7149,
                    maxKey = 19,
                    buildDps = 342300,
                    popularWeapon = "Blood Knight's Warblade",
                    weaponUsage = 57.2,
                    sourceURL = "https://www.archon.gg/wow/builds/unholy/death-knight/mythic-plus/talents/high-keys/all-dungeons/this-week",
                    gearURL = "https://www.archon.gg/wow/builds/unholy/death-knight/mythic-plus/gear-and-tier-set/high-keys/all-dungeons/this-week",
                },
            },
        },
    },
}

DKM.MetaData = MetaData
