-- Static smoke test for DK Mentor 3.0.11 Core UI/HUD regressions.
local file = assert(io.open("Core.lua", "r"))
local core = file:read("*a")
file:close()
local mentorFile = assert(io.open("MentorEngine.lua", "r"))
local mentor = mentorFile:read("*a")
mentorFile:close()
local toolsFile = assert(io.open("DKTools.lua", "r"))
local tools = toolsFile:read("*a")
toolsFile:close()

local normalizePos = assert(core:find('local function NormalizeResourceVisibilityMode', 1, true), 'visibility normalizer missing')
local updatePos = assert(core:find('function addon:UpdateResourceHUD', 1, true), 'UpdateResourceHUD missing')
assert(normalizePos < updatePos, 'visibility normalizer must be declared before UpdateResourceHUD')
assert(not core:find('✓', 1, true), 'unsupported checkmark glyph must not return')
assert(core:find('DKM.CreateActionButton = CreateActionButton', 1, true), 'shared flat action button factory missing')
assert(not core:find('UIPanelButtonTemplate', 1, true), 'Core action buttons must not fall back to red UIPanel buttons')
assert(core:find('SetActionButtonSelected(button, isSelected)', 1, true), 'language picker visual selection missing')
assert(core:find('coachFrame.hasVisibleCards', 1, true), 'live coach visible-card state missing')
assert(core:find('DK Toolkit — reference', 1, true), 'static combat reference must be labeled DK Toolkit')
assert(mentor:find('local allowFallback = mode ~= "essential" or self.hudPreviewMode == true', 1, true), 'Essential urgent-only fallback rule missing')
assert(mentor:find('Live Mentor preview — %s', 1, true), 'HUD preview title clarification missing')

assert(core:find('hud.buildButton:SetSize(190, 24)', 1, true), 'compact HUD settings button width missing')
assert(core:find('T("DK status: ON")', 1, true), 'compact HUD status label missing')
assert(core:find('fontString:SetWordWrap(false)', 1, true), 'HUD toggle labels must stay single-line')
assert(core:find('Alert preview active for 4 seconds.', 1, true), 'alert preview duration must be short')
assert(mentor:find('setupSettingsButton:SetText(T("Setup..."))', 1, true), 'persistent setup wizard button missing from Settings')
assert(tools:find('f:SetSize(136, 22)', 1, true), 'melee warning must remain compact')
assert(tools:find('local MELEE_WARNING_DELAY = 0.30', 1, true), 'melee warning debounce missing')
assert(core:find('entry.kind == "rotation"', 1, true), "Pinned next-action card styling guard missing")
assert(core:find('card:SetBackdropBorderColor(0.25, 0.72, 0.88, 0.92)', 1, true), "Pinned next-action card cyan border missing")


assert(core:find('function addon:GetRelevantRotationSpells()', 1, true), 'spec-aware Assisted Combat filter missing')
assert(core:find('local restrictions = Data.assistedCombatSpecRestrictions or {}', 1, true), 'Assisted Combat spec restrictions missing')
assert(core:find('local rotationSpells = self:GetRelevantRotationSpells()', 1, true), 'action-bar coverage must use filtered rotation spells')
local dataFile = assert(io.open("Data.lua", "r"))
local dataSource = dataFile:read("*a")
dataFile:close()
assert(dataSource:find('Data.assistedCombatSpecRestrictions', 1, true), 'Assisted Combat restriction table missing')
assert(dataSource:find('[343294] = 252', 1, true), 'Soul Reaper must be restricted to Unholy coverage')

print('DK Mentor 3.0.11 Core UX smoke test passed')
