local f = assert(io.open("TalentTree.lua", "r"))
local tree = f:read("*a")
f:close()

assert(tree:find("local TREE_HEIGHT = 575", 1, true), "r9 tree canvas height regression")
assert(tree:find("local HEADER_HEIGHT = 105", 1, true), "r9 tree diagnostic header height regression")
assert(tree:find("local NODE_PADDING = 16", 1, true), "r6 tree padding regression")
assert(tree:find("local scaleX = width / spanX", 1, true), "r6 must fit the horizontal axis independently")
assert(tree:find("local scaleY = height / spanY", 1, true), "r6 must fit the vertical axis independently")
assert(not tree:find("local scale = math.min(width / spanX, height / spanY)", 1, true), "uniform tree scaling must not return")
assert(tree:find("local distributableWidth = math.max(240, innerWidth - (GROUP_GAP * 2))", 1, true), "r6 panel-width distribution missing")
assert(tree:find("local classWidth = math.floor(distributableWidth * 0.40)", 1, true), "class tree must receive 40 percent")
assert(tree:find("local heroWidth = math.floor(distributableWidth * 0.20)", 1, true), "hero tree must receive 20 percent")
assert(tree:find("local specWidth = distributableWidth - classWidth - heroWidth", 1, true), "spec tree must receive the remaining width")

assert(tree:find("DKM.CreateActionButton(parent", 1, true), "r11 tree actions must reuse DK Mentor button styling")
assert(tree:find("local TREE_ACTION_BUTTON_HEIGHT = 28", 1, true), "r11 tree action height regression")
assert(tree:find("math.ceil(textWidth) + TREE_ACTION_BUTTON_PAD_X", 1, true), "r11 tree actions must size to localized text")
assert(tree:find("frame.openButton = CreateTreeActionButton", 1, true), "Open Talents must use DK Mentor action styling")
assert(tree:find("frame.createButton = CreateTreeActionButton", 1, true), "Clone in WoW must use DK Mentor action styling")
assert(tree:find("frame.exportButton = CreateTreeActionButton", 1, true), "Export must use DK Mentor action styling")
assert(tree:find("frame.saveButton = CreateTreeActionButton", 1, true), "Save must use DK Mentor action styling")
assert(tree:find("frame.savedButton = CreateTreeActionButton", 1, true), "Saved must use DK Mentor action styling")
assert(not tree:find("UIPanelButtonTemplate", 1, true), "red Blizzard UIPanel buttons must not return anywhere in TalentTree")

print("DK Mentor 3.3 talent-tree layout/action-button smoke test passed")
